# CSC 4792 ASSIGNMENT #2: MINI PROJECT
## GROUP PROJECT NAME: PROJECT 37
## GROUP MEMBERS;
* IMMANUEL NGWIRA - 2021485897
* DAVIES NGÁ'MBI - 2021411419
* ADESS PHIRI -
* AGNESS
* PHI
 ## Stage 1: Source Inventory
This section documents the official digital sources used to construct
the Rufunsa Town Council dataset.

In [54]:
import os

# Create project folders
os.makedirs("../data/raw", exist_ok=True)
os.makedirs("../data/cleaned", exist_ok=True)
os.makedirs("../documents", exist_ok=True)

print("Project folders created successfully.")

Project folders created successfully.

In [3]:
import pandas as pd

sources = [
    {
        "source_id": "SRC001",
        "title": "Rufunsa Town Council Official Website",
        "url": "https://www.rufunsacouncil.gov.zm/",
        "source_type": "Website",
        "year": "2026",
        "data_category": "General",
        "description": "Official digital footprint of Rufunsa Town Council."
    },

    {
        "source_id": "SRC002",
        "title": "Rufunsa Town Council CDF",
        "url": "https://www.rufunsacouncil.gov.zm/?page_id=4736",
        "source_type": "Web page",
        "year": "2025-2026",
        "data_category": "CDF",
        "description": "CDF projects, bursaries, empowerment, skills development and roads."
    },

    {
        "source_id": "SRC003",
        "title": "WDC Community Project Submissions 2024",
        "url": "https://www.rufunsacouncil.gov.zm/wp-content/uploads/2024/11/WDC-Submissions-2024-Community-Projects-Rufunsa.pdf",
        "source_type": "PDF",
        "year": "2024",
        "data_category": "CDF Projects",
        "description": "Ward Development Committee submissions for community projects."
    },

    {
        "source_id": "SRC004",
        "title": "Rufunsa Integrated Development Plan",
        "url": "https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/11/RUFUNSA_IDP_2024-April2025-1-2-1.pdf",
        "source_type": "PDF",
        "year": "2024-2034",
        "data_category": "Development and Finance",
        "description": "IDP containing development, financial, revenue and implementation information."
    },

    {
        "source_id": "SRC005",
        "title": "Rufunsa Constituency and Wards",
        "url": "https://www.rufunsacouncil.gov.zm/?page_id=7384",
        "source_type": "Web page",
        "year": "2026",
        "data_category": "Administrative",
        "description": "Information about Rufunsa Constituency and its 12 wards."
    },

    {
        "source_id": "SRC006",
        "title": "Rufunsa Town Council Publications",
        "url": "https://www.rufunsacouncil.gov.zm/?page_id=959",
        "source_type": "Web page",
        "year": "2026",
        "data_category": "Documents",
        "description": "Council publications, plans, guidelines and reports."
    },

    {
        "source_id": "SRC007",
        "title": "Rufunsa Town Council Civic Leaders",
        "url": "https://www.rufunsacouncil.gov.zm/?page_id=4763",
        "source_type": "Web page",
        "year": "2026",
        "data_category": "Administrative",
        "description": "Information about council civic leaders and councillors."
    },

    {
        "source_id": "SRC008",
        "title": "Rufunsa Town Council Departments",
        "url": "https://www.rufunsacouncil.gov.zm/?page_id=770",
        "source_type": "Web page",
        "year": "2026",
        "data_category": "Administrative",
        "description": "Council departments and institutional functions."
    }
]

sources_df = pd.DataFrame(sources)

sources_df

,source_id,title,url,source_type,year,data_category,description
0,SRC001,Rufunsa Town Council Official Website,https://www.rufunsacouncil.gov.zm/,Website,2026,General,Official digital footprint of Rufunsa Town Cou...
1,SRC002,Rufunsa Town Council CDF,https://www.rufunsacouncil.gov.zm/?page_id=4736,Web page,2025-2026,CDF,"CDF projects, bursaries, empowerment, skills d..."
2,SRC003,WDC Community Project Submissions 2024,https://www.rufunsacouncil.gov.zm/wp-content/u...,PDF,2024,CDF Projects,Ward Development Committee submissions for com...
3,SRC004,Rufunsa Integrated Development Plan,https://www.rufunsacouncil.gov.zm/wp-content/u...,PDF,2024-2034,Development and Finance,"IDP containing development, financial, revenue..."
4,SRC005,Rufunsa Constituency and Wards,https://www.rufunsacouncil.gov.zm/?page_id=7384,Web page,2026,Administrative,Information about Rufunsa Constituency and its...
5,SRC006,Rufunsa Town Council Publications,https://www.rufunsacouncil.gov.zm/?page_id=959,Web page,2026,Documents,"Council publications, plans, guidelines and re..."
6,SRC007,Rufunsa Town Council Civic Leaders,https://www.rufunsacouncil.gov.zm/?page_id=4763,Web page,2026,Administrative,Information about council civic leaders and co...
7,SRC008,Rufunsa Town Council Departments,https://www.rufunsacouncil.gov.zm/?page_id=770,Web page,2026,Administrative,Council departments and institutional functions.

In [4]:
source_file = "../data/raw/rufunsa_sources.csv"

sources_df.to_csv(
    source_file,
    sep="|",
    index=False
)

print("Source inventory saved to:")
print(source_file)

Source inventory saved to:
../data/raw/rufunsa_sources.csv

In [7]:
import pandas as pd
import requests
import os
import pdfplumber

from bs4 import BeautifulSoup
from urllib.parse import urljoin

In [8]:
cdf_url = "https://www.rufunsacouncil.gov.zm/?page_id=4736"

response = requests.get(
    cdf_url,
    verify=False
)

print("Status code:", response.status_code)

C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.rufunsacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status code: 200

In [9]:
soup = BeautifulSoup(response.text, "html.parser")

links = []

for a in soup.find_all("a", href=True):
    links.append({
        "title": a.get_text(" ", strip=True),
        "url": urljoin(cdf_url, a["href"])
    })

links_df = pd.DataFrame(links)

print("Total links found:", len(links_df))

links_df.head()

Total links found: 91

         title                                               url
0               https://www.rufunsacouncil.gov.zm/?page_id=4736#
1         Home                https://www.rufunsacouncil.gov.zm/
2     About Us  https://www.rufunsacouncil.gov.zm/?page_id=4736#
3   Who we are    https://www.rufunsacouncil.gov.zm/?page_id=118
4  Departments    https://www.rufunsacouncil.gov.zm/?page_id=770

In [10]:
cdf_links = links_df[
    links_df["title"].str.contains(
        "2026 CDF COMMUNITY PROJECTS|"
        "2025 CDF COMMUNITY PROJECTS|"
        "2025 CDF PROJECTS RECEIVED FROM WDCs|"
        "NOTIFICATION OF APPROVAL OF 2025 CDF COMMUNITY PROJECTS|"
        "LIST OF 2025 APPROVED CDF COMMUNITY PROJECTS|"
        "LIST OF NON-APPROVED PROJECTS FROM ALL THE 12 WARDS|"
        "2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED|"
        "2025 APPROVED EMPOWERMENT GRANTS|"
        "2025 CDF ROADS FOR GRADING PROJECTS|"
        "VIEW CDF COMMUNITY PROJECTS FROM 2022 TO 2025",
        case=False,
        na=False
    )
].reset_index(drop=True)

cdf_links

,title,url
0,2026 CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/?page_id=4736
1,2025 CDF PROJECTS RECEIVED FROM WDCs,https://www.rufunsacouncil.gov.zm/wp-content/u...
2,NOTIFICATION OF APPROVAL OF 2025 CDF COMMUNITY...,https://www.rufunsacouncil.gov.zm/wp-content/u...
3,LIST OF 2025 APPROVED CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/u...
4,LIST OF NON-APPROVED PROJECTS FROM ALL THE 12 ...,https://www.rufunsacouncil.gov.zm/wp-content/u...
5,2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED,https://www.rufunsacouncil.gov.zm/wp-content/u...
6,2025 APPROVED EMPOWERMENT GRANTS,https://www.rufunsacouncil.gov.zm/wp-content/u...
7,2025 CDF ROADS FOR GRADING PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/u...
8,VIEW CDF COMMUNITY PROJECTS FROM 2022 TO 2025,https://www.rufunsacouncil.gov.zm/?page_id=932

In [11]:
cdf_links.to_csv(
    "../data/raw/rufunsa_cdf_links.csv",
    sep="|",
    index=False
)

print("CDF links saved successfully.")

CDF links saved successfully.

In [14]:
cdf_links = pd.read_csv(
    "../data/raw/rufunsa_cdf_links.csv",
    sep="|"
)

cdf_links

,title,url
0,2026 CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/?page_id=4736
1,2025 CDF PROJECTS RECEIVED FROM WDCs,https://www.rufunsacouncil.gov.zm/wp-content/u...
2,NOTIFICATION OF APPROVAL OF 2025 CDF COMMUNITY...,https://www.rufunsacouncil.gov.zm/wp-content/u...
3,LIST OF 2025 APPROVED CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/u...
4,LIST OF NON-APPROVED PROJECTS FROM ALL THE 12 ...,https://www.rufunsacouncil.gov.zm/wp-content/u...
5,2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED,https://www.rufunsacouncil.gov.zm/wp-content/u...
6,2025 APPROVED EMPOWERMENT GRANTS,https://www.rufunsacouncil.gov.zm/wp-content/u...
7,2025 CDF ROADS FOR GRADING PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/u...
8,VIEW CDF COMMUNITY PROJECTS FROM 2022 TO 2025,https://www.rufunsacouncil.gov.zm/?page_id=932

In [16]:
if file_type == "PDF":
    extension = ".pdf"

elif file_type == "Excel":
    extension = ".xlsx"

elif file_type == "Word":
    extension = ".docx"

else:
    extension = ".html"


raw_filename = (
    "2025_cdf_projects_received_from_wdcs"
    + extension
)

raw_path = os.path.join(
    "../data/raw",
    raw_filename
)

with open(raw_path, "wb") as file:
    file.write(response.content)

print("Saved:", raw_path)

Saved: ../data/raw\2025_cdf_projects_received_from_wdcs.html

In [17]:
if file_type == "PDF":

    print("Extracting PDF...")

    with pdfplumber.open(raw_path) as pdf:

        print("Number of pages:", len(pdf.pages))

        pdf_text = ""

        for page_number, page in enumerate(pdf.pages, start=1):

            text = page.extract_text()

            if text:
                pdf_text += (
                    f"\n--- PAGE {page_number} ---\n"
                )
                pdf_text += text

    print(pdf_text[:5000])

In [18]:
if file_type == "PDF":

    all_tables = []

    with pdfplumber.open(raw_path) as pdf:

        for page_number, page in enumerate(
            pdf.pages,
            start=1
        ):

            tables = page.extract_tables()

            for table in tables:

                if table:
                    table_df = pd.DataFrame(table)

                    table_df["page"] = page_number

                    all_tables.append(table_df)

    print("Number of tables found:", len(all_tables))

# Combining the extracted PDF tables
    if file_type == "PDF" and all_tables:

    pdf_data = pd.concat(
        all_tables,
        ignore_index=True
    )

    pdf_data.head(20)

In [19]:
if file_type == "PDF":

    print("Shape:", pdf_data.shape)

    print("\nColumns:")
    print(pdf_data.columns.tolist())

    print("\nFirst records:")
    display(pdf_data.head(20))

In [20]:
if file_type == "Excel":

    excel_file = pd.ExcelFile(raw_path)

    print(
        "Available sheets:",
        excel_file.sheet_names
    )

In [21]:
if file_type == "Excel":

    df_projects = pd.read_excel(
        raw_path,
        sheet_name=excel_file.sheet_names[0]
    )

    display(df_projects.head(20))

In [22]:
if file_type == "Excel":

    print("Shape:", df_projects.shape)

    print("\nColumns:")
    print(df_projects.columns.tolist())

    print("\nData types:")
    print(df_projects.dtypes)

    print("\nMissing values:")
    print(df_projects.isnull().sum())

In [23]:
if file_type == "PDF" and all_tables:

    extracted_df = pdf_data

elif file_type == "Excel":

    extracted_df = df_projects

else:

    extracted_df = None

In [24]:
if extracted_df is not None:

    print(
        "Extracted dataset shape:",
        extracted_df.shape
    )

    display(extracted_df.head(20))

In [25]:
if extracted_df is not None:

    extracted_df.columns = (
        extracted_df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("/", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )

    print(extracted_df.columns.tolist())

In [26]:
extracted_df = extracted_df.dropna(
    how="all"
)

print(
    "Rows after removing empty rows:",
    len(extracted_df)
)

AttributeError: 'NoneType' object has no attribute 'dropna'

In [31]:
import pandas as pd

cdf_links = pd.read_csv(
    "../data/raw/rufunsa_cdf_links.csv",
    sep="|"
)

print(cdf_links)

                                               title  \
0                        2026 CDF COMMUNITY PROJECTS
1               2025 CDF PROJECTS RECEIVED FROM WDCs
2  NOTIFICATION OF APPROVAL OF 2025 CDF COMMUNITY...
3       LIST OF 2025 APPROVED CDF COMMUNITY PROJECTS
4  LIST OF NON-APPROVED PROJECTS FROM ALL THE 12 ...
5      2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED
6                   2025 APPROVED EMPOWERMENT GRANTS
7                2025 CDF ROADS FOR GRADING PROJECTS
8      VIEW CDF COMMUNITY PROJECTS FROM 2022 TO 2025

                                                 url
0    https://www.rufunsacouncil.gov.zm/?page_id=4736
1  https://www.rufunsacouncil.gov.zm/wp-content/u...
2  https://www.rufunsacouncil.gov.zm/wp-content/u...
3  https://www.rufunsacouncil.gov.zm/wp-content/u...
4  https://www.rufunsacouncil.gov.zm/wp-content/u...
5  https://www.rufunsacouncil.gov.zm/wp-content/u...
6  https://www.rufunsacouncil.gov.zm/wp-content/u...
7  https://www.rufunsacouncil.gov.zm/wp-content/u...
8     https://www.rufunsacouncil.gov.zm/?page_id=932

In [32]:
source = cdf_links[
    cdf_links["title"].str.contains(
        "2025 CDF PROJECTS RECEIVED FROM WDCs",
        case=False,
        na=False
    )
].reset_index(drop=True)

print(source)

                                  title  \
0  2025 CDF PROJECTS RECEIVED FROM WDCs

                                                 url
0  https://www.rufunsacouncil.gov.zm/wp-content/u...

In [33]:
print("Number of matching sources:", len(source))

Number of matching sources: 1

In [34]:
source_url = source["url"].iloc[0]

print("Source title:")
print(source["title"].iloc[0])

print("\nSource URL:")
print(source_url)

Source title:
2025 CDF PROJECTS RECEIVED FROM WDCs

Source URL:
https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/01/2025-Community-Project-Applications-_-Received.xlsx

In [35]:
import requests

response = requests.get(
    source_url,
    verify=False
)

print("Status code:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))
print("Final URL:", response.url)

Status code: 200
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Final URL: https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/01/2025-Community-Project-Applications-_-Received.xlsx

C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.rufunsacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [36]:
import os

raw_path = "../data/raw/2025_cdf_projects_received_from_wdcs.xlsx"

with open(raw_path, "wb") as f:
    f.write(response.content)

print("File saved successfully.")
print(raw_path)

File saved successfully.
../data/raw/2025_cdf_projects_received_from_wdcs.xlsx

In [37]:
print(os.path.exists(raw_path))

True

In [38]:
excel_file = pd.ExcelFile(raw_path)

print("Sheets in the Excel file:")
print(excel_file.sheet_names)

Sheets in the Excel file:
['All Apps', 'Priorities Per Ward', 'Security', 'Health ', 'Education', 'Water', 'Roads']

In [39]:
extracted_df = pd.read_excel(
    raw_path,
    sheet_name=excel_file.sheet_names[0]
)

print("Data extracted successfully.")
print("Rows:", extracted_df.shape[0])
print("Columns:", extracted_df.shape[1])

Data extracted successfully.
Rows: 99
Columns: 14

In [40]:
extracted_df.head(10)

,MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,RUFUNSA CONSTITUENCY DEVELOPMENT FUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025 COMMUNITY PROJECTS APPLICATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No.,Ward,Zone,Name of Project,Project Description,Order of Priority Per Ward,Sector,Type,Number of Beneficiaries,CDF Application Form (Yes/No),WDEC Recommendation (Yes/No),WDC Minutes (Yes/No),Zonal Minutes (Yes/No),Appraisal Comment
3,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,NaN,Water,Water,120,Yes,Yes,Yes,No,NaN
4,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,NaN,Education,Library,2438,Yes,Yes,Yes,Yes,NaN
5,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,NaN,Education,Classroom Block,4800,Yes,Yes,Yes,Yes,NaN
6,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,NaN,Education,Classroom Block,517,Yes,Yes,Yes,Yes,NaN
7,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,NaN,Road,Bridge,150,Yes,No,Yes,Yes,NaN
8,6,Kankumba,Kankumba,"Construction of 1X3 Classroom Block, Staff Hou...","Construction of 1X3 CRB, Staff House and a Bor...",NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN
9,7,Kankumba,Kanyongoloka,Construction of 1X3 Classroom Block at Chipokolo,Construction of 1X3 Classroom Block at Chipokolo,NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN

In [41]:
extracted_df = extracted_df.dropna(how="all")

extracted_df = extracted_df.dropna(
    axis=1,
    how="all"
)

extracted_df = extracted_df.drop_duplicates()

print("Cleaning completed.")
print("Rows:", extracted_df.shape[0])
print("Columns:", extracted_df.shape[1])

Cleaning completed.
Rows: 99
Columns: 14

In [42]:
extracted_df.head(10)

,MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,RUFUNSA CONSTITUENCY DEVELOPMENT FUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025 COMMUNITY PROJECTS APPLICATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No.,Ward,Zone,Name of Project,Project Description,Order of Priority Per Ward,Sector,Type,Number of Beneficiaries,CDF Application Form (Yes/No),WDEC Recommendation (Yes/No),WDC Minutes (Yes/No),Zonal Minutes (Yes/No),Appraisal Comment
3,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,NaN,Water,Water,120,Yes,Yes,Yes,No,NaN
4,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,NaN,Education,Library,2438,Yes,Yes,Yes,Yes,NaN
5,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,NaN,Education,Classroom Block,4800,Yes,Yes,Yes,Yes,NaN
6,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,NaN,Education,Classroom Block,517,Yes,Yes,Yes,Yes,NaN
7,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,NaN,Road,Bridge,150,Yes,No,Yes,Yes,NaN
8,6,Kankumba,Kankumba,"Construction of 1X3 Classroom Block, Staff Hou...","Construction of 1X3 CRB, Staff House and a Bor...",NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN
9,7,Kankumba,Kanyongoloka,Construction of 1X3 Classroom Block at Chipokolo,Construction of 1X3 Classroom Block at Chipokolo,NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN

In [43]:
print(extracted_df.columns.tolist())

['MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [44]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 50)

extracted_df.head(15)

,MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,RUFUNSA CONSTITUENCY DEVELOPMENT FUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025 COMMUNITY PROJECTS APPLICATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No.,Ward,Zone,Name of Project,Project Description,Order of Priority Per Ward,Sector,Type,Number of Beneficiaries,CDF Application Form (Yes/No),WDEC Recommendation (Yes/No),WDC Minutes (Yes/No),Zonal Minutes (Yes/No),Appraisal Comment
3,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,NaN,Water,Water,120,Yes,Yes,Yes,No,NaN
4,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,NaN,Education,Library,2438,Yes,Yes,Yes,Yes,NaN
5,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,NaN,Education,Classroom Block,4800,Yes,Yes,Yes,Yes,NaN
6,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,NaN,Education,Classroom Block,517,Yes,Yes,Yes,Yes,NaN
7,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,NaN,Road,Bridge,150,Yes,No,Yes,Yes,NaN
8,6,Kankumba,Kankumba,"Construction of 1X3 Classroom Block, Staff Hou...","Construction of 1X3 CRB, Staff House and a Bor...",NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN
9,7,Kankumba,Kanyongoloka,Construction of 1X3 Classroom Block at Chipokolo,Construction of 1X3 Classroom Block at Chipokolo,NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN
10,8,Kankumba,Mwambashi,Construction of Staff House at Mwambashi Prima...,Construction of Staff House at Mwambashi Prima...,NaN,Education,Staff House,1200,Yes,Yes,Yes,Yes,NaN
11,9,Kankumba,Mwambashi,Construction of 2X2 VIP Toilets at Mwambashi H...,Construction of 2X2 VIP Toilets at Mwambashi H...,NaN,Health,VIP Toilets,4628,Yes,Yes,Yes,Yes,NaN
12,10,Kankumba,Mwambashi,Construction of 1X3 Classroom Block at Chinyik...,Construction of 1X3 Classroom Block at Chinyik...,NaN,Education,Classroom Block,2743,Yes,Yes,Yes,Yes,NaN
13,11,Kankumba,Kankumba,Procurement of Laboratory Assoceries at Kankum...,Procurement of Laboratory Assoceries at Kankum...,NaN,Education,Equipment and Chemicals,2000,Yes,Yes,Yes,Yes,NaN
14,12,Kankumba,Kanyongoloka,Rehabilitation of Mukonka Health Post,Rehabilitation of Mukonka Health Post,NaN,Health,Health Post,4200,Yes,Yes,Yes,Yes,NaN

In [45]:
print(extracted_df.shape)

(99, 14)

In [49]:
print(excel_file.sheet_names)

['All Apps', 'Priorities Per Ward', 'Security', 'Health ', 'Education', 'Water', 'Roads']

In [50]:
test_df = pd.read_excel(
    raw_path,
    sheet_name=excel_file.sheet_names[0],
    header=None
)

print(test_df.shape)

(100, 14)

In [51]:
for i in range(5):
    print(f"\nROW {i}")
    print(test_df.iloc[i].tolist())

ROW 0
['MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

ROW 1
['RUFUNSA CONSTITUENCY DEVELOPMENT FUND', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

ROW 2
['2025 COMMUNITY PROJECTS APPLICATIONS', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

ROW 3
['No.', 'Ward', 'Zone', 'Name of Project', 'Project Description', 'Order of Priority Per Ward', 'Sector', 'Type', 'Number of Beneficiaries', 'CDF Application Form (Yes/No)', 'WDEC Recommendation (Yes/No)', 'WDC Minutes (Yes/No)', 'Zonal Minutes (Yes/No)', 'Appraisal Comment']

ROW 4
[1, 'Kankumba', 'Mwambashi', 'Waterborne sanitation System in Mwalubemba Community', 'Construction of waterborne sanitation system at Mwalubemba Community.', nan, 'Water', 'Water', 120, 'Yes', 'Yes', 'Yes', 'No', nan]

In [53]:
# Get the column headings from row 3
headers = test_df.iloc[3].tolist()

# Get the actual project data starting from row 4
extracted_df = test_df.iloc[4:].copy()

# Assign the correct column headings
extracted_df.columns = headers

# Reset the row numbers
extracted_df = extracted_df.reset_index(drop=True)

print("Columns:")
print(extracted_df.columns.tolist())

Columns:
['No.', 'Ward', 'Zone', 'Name of Project', 'Project Description', 'Order of Priority Per Ward', 'Sector', 'Type', 'Number of Beneficiaries', 'CDF Application Form (Yes/No)', 'WDEC Recommendation (Yes/No)', 'WDC Minutes (Yes/No)', 'Zonal Minutes (Yes/No)', 'Appraisal Comment']

In [54]:
extracted_df.head(10)

,No.,Ward,Zone,Name of Project,Project Description,Order of Priority Per Ward,Sector,Type,Number of Beneficiaries,CDF Application Form (Yes/No),WDEC Recommendation (Yes/No),WDC Minutes (Yes/No),Zonal Minutes (Yes/No),Appraisal Comment
0,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,NaN,Water,Water,120,Yes,Yes,Yes,No,NaN
1,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,NaN,Education,Library,2438,Yes,Yes,Yes,Yes,NaN
2,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,NaN,Education,Classroom Block,4800,Yes,Yes,Yes,Yes,NaN
3,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,NaN,Education,Classroom Block,517,Yes,Yes,Yes,Yes,NaN
4,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,NaN,Road,Bridge,150,Yes,No,Yes,Yes,NaN
5,6,Kankumba,Kankumba,"Construction of 1X3 Classroom Block, Staff Hou...","Construction of 1X3 CRB, Staff House and a Bor...",NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN
6,7,Kankumba,Kanyongoloka,Construction of 1X3 Classroom Block at Chipokolo,Construction of 1X3 Classroom Block at Chipokolo,NaN,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,NaN
7,8,Kankumba,Mwambashi,Construction of Staff House at Mwambashi Prima...,Construction of Staff House at Mwambashi Prima...,NaN,Education,Staff House,1200,Yes,Yes,Yes,Yes,NaN
8,9,Kankumba,Mwambashi,Construction of 2X2 VIP Toilets at Mwambashi H...,Construction of 2X2 VIP Toilets at Mwambashi H...,NaN,Health,VIP Toilets,4628,Yes,Yes,Yes,Yes,NaN
9,10,Kankumba,Mwambashi,Construction of 1X3 Classroom Block at Chinyik...,Construction of 1X3 Classroom Block at Chinyik...,NaN,Education,Classroom Block,2743,Yes,Yes,Yes,Yes,NaN

## Remove completely empty rows;

In [56]:
extracted_df = extracted_df.dropna(how="all")

# Remove completely empty columns:
extracted_df = extracted_df.dropna(
    axis=1,
    how="all"
)

# Remove duplicate records:
extracted_df = extracted_df.drop_duplicates()

In [57]:
print("Rows:", extracted_df.shape[0])
print("Columns:", extracted_df.shape[1])

Rows: 96
Columns: 12

In [58]:
# Standardize the column names
extracted_df.columns = (
    extracted_df.columns
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("-", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

In [59]:
print(extracted_df.columns.tolist())

['no.', 'ward', 'zone', 'name_of_project', 'project_description', 'sector', 'type', 'number_of_beneficiaries', 'cdf_application_form_yes_no', 'wdec_recommendation_yes_no', 'wdc_minutes_yes_no', 'zonal_minutes_yes_no']

In [60]:
# Rename important columns
extracted_df = extracted_df.rename(
    columns={
        "no.": "project_id",
        "name_of_project": "project_name",
        "type": "project_type",
        "number_of_beneficiaries": "beneficiaries"
    }
)

In [61]:
extracted_df.head()

,project_id,ward,zone,project_name,project_description,sector,project_type,beneficiaries,cdf_application_form_yes_no,wdec_recommendation_yes_no,wdc_minutes_yes_no,zonal_minutes_yes_no
0,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,Water,Water,120,Yes,Yes,Yes,No
1,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,Education,Library,2438,Yes,Yes,Yes,Yes
2,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,Education,Classroom Block,4800,Yes,Yes,Yes,Yes
3,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,Education,Classroom Block,517,Yes,Yes,Yes,Yes
4,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,Road,Bridge,150,Yes,No,Yes,Yes

## Adding Rufunsa information:

In [65]:

extracted_df["council"] = "Rufunsa Town Council"
extracted_df["province"] = "Lusaka Province"
extracted_df["district"] = "Rufunsa"
extracted_df["constituency"] = "Rufunsa"
extracted_df["financial_year"] = 2025

## Adding source/provenance information

In [66]:
extracted_df["source_url"] = source_url

extracted_df["source_document"] = (
    "2025 CDF Projects Received from WDCs"
)

extracted_df["retrieval_date"] = (
    pd.Timestamp.today().strftime("%Y-%m-%d")
)

In [67]:
print("Final dataset shape:")
print(extracted_df.shape)

print("\nColumns:")
print(extracted_df.columns.tolist())

print("\nMissing values:")
print(extracted_df.isnull().sum())

print("\nDuplicate rows:")
print(extracted_df.duplicated().sum())

Final dataset shape:
(96, 20)

Columns:
['project_id', 'ward', 'zone', 'project_name', 'project_description', 'sector', 'project_type', 'beneficiaries', 'cdf_application_form_yes_no', 'wdec_recommendation_yes_no', 'wdc_minutes_yes_no', 'zonal_minutes_yes_no', 'council', 'province', 'district', 'constituency', 'financial_year', 'source_url', 'source_document', 'retrieval_date']

Missing values:
project_id                     0
ward                           0
zone                           0
project_name                   1
project_description            1
sector                         1
project_type                   1
beneficiaries                  1
cdf_application_form_yes_no    0
wdec_recommendation_yes_no     0
wdc_minutes_yes_no             0
zonal_minutes_yes_no           0
council                        0
province                       0
district                       0
constituency                   0
financial_year                 0
source_url                     0
source_document                0
retrieval_date                 0
dtype: int64

Duplicate rows:
0

In [68]:
display(extracted_df.head(20))

,project_id,ward,zone,project_name,project_description,sector,project_type,beneficiaries,cdf_application_form_yes_no,wdec_recommendation_yes_no,wdc_minutes_yes_no,zonal_minutes_yes_no,council,province,district,constituency,financial_year,source_url,source_document,retrieval_date
0,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,Water,Water,120,Yes,Yes,Yes,No,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
1,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,Education,Library,2438,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
2,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,Education,Classroom Block,4800,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
3,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,Education,Classroom Block,517,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
4,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,Road,Bridge,150,Yes,No,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
5,6,Kankumba,Kankumba,"Construction of 1X3 Classroom Block, Staff Hou...","Construction of 1X3 CRB, Staff House and a Bor...",Education,Classroom Block,1000,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
6,7,Kankumba,Kanyongoloka,Construction of 1X3 Classroom Block at Chipokolo,Construction of 1X3 Classroom Block at Chipokolo,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
7,8,Kankumba,Mwambashi,Construction of Staff House at Mwambashi Prima...,Construction of Staff House at Mwambashi Prima...,Education,Staff House,1200,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
8,9,Kankumba,Mwambashi,Construction of 2X2 VIP Toilets at Mwambashi H...,Construction of 2X2 VIP Toilets at Mwambashi H...,Health,VIP Toilets,4628,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
9,10,Kankumba,Mwambashi,Construction of 1X3 Classroom Block at Chinyik...,Construction of 1X3 Classroom Block at Chinyik...,Education,Classroom Block,2743,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
10,11,Kankumba,Kankumba,Procurement of Laboratory Assoceries at Kankum...,Procurement of Laboratory Assoceries at Kankum...,Education,Equipment and Chemicals,2000,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
11,12,Kankumba,Kanyongoloka,Rehabilitation of Mukonka Health Post,Rehabilitation of Mukonka Health Post,Health,Health Post,4200,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
12,13,Mankhanda,Lukwipa,Construction of a Health facility at Lukwipa,Construction of a Health facility,Health,Health facility,4969,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
13,14,Mankhanda,Lukwipa,Drilling of a Borehole in Saffalau Village,Drilling of a Borehole,Water,Water sector,200,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
14,15,Mankhanda,Lukwipa,Rehabilitation of an incomplete Borehole (fitt...,Rehabilitation of an incomplete Borehole,Water,Water sector,250,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
15,16,Mankhanda,Lukwipa,Completion of the Girl's dormitory at Lukwipa ...,Completion of the Girl's dorminitory,Education,Dorminitory,500,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
16,17,Mankhanda,Lukwipa,200 Bunker beds for Lukwipa secondary school,200 bunker beds,Education,Bunker beds,450,yes,yes,yes,yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
17,18,Mankhanda,Kampishi,Construction of a staff house 1x2 semi detache...,Construction of a staff house 1x2 semi detache...,Education,Staff House,NaN,Yes,Yes,Yes,yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
18,19,Mankhanda,Menyani Village,Borehole in Menyani Village,Borehole,Water,Water sector,800,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
19,20,Mankhanda,Christian Family Church,Construction of 1x3 classroom block at Mankhan...,Construction of a 1x3 classroom block,Education,Classroom Block,1500,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14

## Saving the required pipe-separated CSV

In [69]:
final_path = (
    "../data/cleaned/"
    "db-unza26-csc4792-rufunsa_cdf_community_projects.csv"
)

extracted_df.to_csv(
    final_path,
    sep="|",
    index=False
)

print("Final dataset saved:")
print(final_path)

Final dataset saved:
../data/cleaned/db-unza26-csc4792-rufunsa_cdf_community_projects.csv

In [71]:
check_df = pd.read_csv(
    final_path,
    sep="|"
)

print("Rows:", check_df.shape[0])
print("Columns:", check_df.shape[1])

display(check_df.head(10))

Rows: 96
Columns: 20

,project_id,ward,zone,project_name,project_description,sector,project_type,beneficiaries,cdf_application_form_yes_no,wdec_recommendation_yes_no,wdc_minutes_yes_no,zonal_minutes_yes_no,council,province,district,constituency,financial_year,source_url,source_document,retrieval_date
0,1,Kankumba,Mwambashi,Waterborne sanitation System in Mwalubemba Com...,Construction of waterborne sanitation system a...,Water,Water,120,Yes,Yes,Yes,No,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
1,2,Kankumba,Kankumba,Construction of a community Library and Resour...,Construction and set up of a community library...,Education,Library,2438,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
2,3,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Katop...,Construction of a 1X3 Classroom Block at Katop...,Education,Classroom Block,4800,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
3,4,Kankumba,Kanyongoloka,Construction of a 1X3 Classroom Block at Mukon...,Construction of a 1X3 Classroom Block at Mukon...,Education,Classroom Block,517,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
4,5,Kankumba,Chilimba,Construction of a bridge (Crossing Point) in M...,Construction of a bridge (Crossing Point) in M...,Road,Bridge,150,Yes,No,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
5,6,Kankumba,Kankumba,"Construction of 1X3 Classroom Block, Staff Hou...","Construction of 1X3 CRB, Staff House and a Bor...",Education,Classroom Block,1000,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
6,7,Kankumba,Kanyongoloka,Construction of 1X3 Classroom Block at Chipokolo,Construction of 1X3 Classroom Block at Chipokolo,Education,Classroom Block,1000,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
7,8,Kankumba,Mwambashi,Construction of Staff House at Mwambashi Prima...,Construction of Staff House at Mwambashi Prima...,Education,Staff House,1200,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
8,9,Kankumba,Mwambashi,Construction of 2X2 VIP Toilets at Mwambashi H...,Construction of 2X2 VIP Toilets at Mwambashi H...,Health,VIP Toilets,4628,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14
9,10,Kankumba,Mwambashi,Construction of 1X3 Classroom Block at Chinyik...,Construction of 1X3 Classroom Block at Chinyik...,Education,Classroom Block,2743,Yes,Yes,Yes,Yes,Rufunsa Town Council,Lusaka Province,Rufunsa,Rufunsa,2025,https://www.rufunsacouncil.gov.zm/wp-content/u...,2025 CDF Projects Received from WDCs,2026-09-14

## CDF Bursaries and Empowerment Dataset 
## A. Information to collect
From the Rufunsa Town Council CDF sources, collect information relating to:
Secondary school bursaries
* Skills development bursaries
* Empowerment grants
* Applications received
* Approved beneficiaries
* Programme/category
* Amounts, if provided
* Ward, if provided
* Financial year
* Approval/status
## B. Target columns
Use:
* record_id
* council
* province
* district
* constituency
* ward
* financial_year
* programme_type
* applicant_category
* number_of_beneficiaries
* amount
* status
* source_url
* source_document
* retrieval_date

## C. Extract the source
Loading your CDF links:

In [1]:
import pandas as pd

cdf_links = pd.read_csv(
    "../data/raw/rufunsa_cdf_links.csv",
    sep="|"
)

pd.set_option("display.max_colwidth", None)

display(cdf_links)

,title,url
0,2026 CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/?page_id=4736
1,2025 CDF PROJECTS RECEIVED FROM WDCs,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/01/2025-Community-Project-Applications-_-Received.xlsx
2,NOTIFICATION OF APPROVAL OF 2025 CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/Notification-of-approval-of-2025-CDF-community-projects.pdf
3,LIST OF 2025 APPROVED CDF COMMUNITY PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/05/List-of-approved-projects-for-2025-CDF.docx
4,LIST OF NON-APPROVED PROJECTS FROM ALL THE 12 WARDS,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/Status-of-2025-CDF-Applications-from-all-the-12-Wards.pdf
5,2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/2025-Skills-Development-Applications-Received.pdf
6,2025 APPROVED EMPOWERMENT GRANTS,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/Approved-2025-CDF-Empowerment-Grant.pdf
7,2025 CDF ROADS FOR GRADING PROJECTS,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/05/Approved-Roads-for-Grading-under-the-2025-CDF.doc
8,VIEW CDF COMMUNITY PROJECTS FROM 2022 TO 2025,https://www.rufunsacouncil.gov.zm/?page_id=932

Finding the skills development source:

In [2]:
skills_source = cdf_links[
    cdf_links["title"].str.contains(
        "2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED",
        case=False,
        na=False
    )
]

display(skills_source)

,title,url
5,2025 SKILLS DEVELOPMENT APPLICATIONS RECEIVED,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/2025-Skills-Development-Applications-Received.pdf

Getting the URL:

In [14]:
skills_url = skills_source.iloc[0]["url"]

print(skills_url)

https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/2025-Skills-Development-Applications-Received.pdf

In [15]:
bursary_links = cdf_links[
    cdf_links["title"].str.contains(
        "BURSARY|BURSARIES",
        case=False,
        na=False
    )
]

display(bursary_links[["title", "url"]])

Empty DataFrame
Columns: [title, url]
Index: []

Finding the skills development source:

In [5]:
bursary_source = cdf_links[
    cdf_links["title"].str.contains(
        "2025 APPROVED SECONDARY SCHOOL BURSARIES",
        case=False,
        na=False
    )
]

display(bursary_source)

Empty DataFrame
Columns: [title, url]
Index: []

In [6]:
empowerment_source = cdf_links[
    cdf_links["title"].str.contains(
        "2025 APPROVED EMPOWERMENT GRANTS",
        case=False,
        na=False
    )
]

display(empowerment_source)

,title,url
6,2025 APPROVED EMPOWERMENT GRANTS,https://www.rufunsacouncil.gov.zm/wp-content/uploads/2025/06/Approved-2025-CDF-Empowerment-Grant.pdf

Downloading and identifying the file type

In [8]:
import requests

response = requests.get(
    skills_url,
    verify=False,
    timeout=30
)

print(
    response.headers.get("Content-Type")
)

C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.rufunsacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

application/pdf

If it is Excel

In [43]:
bursary_path = "../data/raw/2025_approved_secondary_school_bursaries.pdf"

with open(bursary_path, "wb") as file:
    file.write(response.content)

print("Saved:", bursary_path)

Saved: ../data/raw/2025_approved_secondary_school_bursaries.pdf

In [44]:
import pdfplumber

with pdfplumber.open(bursary_path) as pdf:

    for page_number, page in enumerate(
        pdf.pages,
        start=1
    ):

        print(
            f"--- PAGE {page_number} ---"
        )

        print(
            page.extract_text()
        )

--- PAGE 1 ---
FARMING FISHING TOURISM
VISION
An industrial hub for tourism, m1n,ng and agriculture through sustainable exploitation of natural
resources in Lusaka province by the year 203411
1
--- PAGE 2 ---
FOREWORD
Rufunsa District takes delight in the compilation of the
Integrated Development Plan (IDP) whose preparation is in line
with the Urban and Regional Planning Act No. 3 of 2015 and
the 8th National Development Plan.
This IDP is not just a manuscript but a document that provides a
valuable window of information, projections, plans and
strategies that will see the already sprouting development grow
into tangible resultswhich demonstrate the positive impact it will
have on our people and all sectors of the district. It is the
principal strategic planning instrument which gives an overall
framework for development in our district and guide and inform
planning, budgeting, management and decision-making by all sectors. The Document places a greater
emphasis on the integration of socio-economic and spatial planning.
The IDP is convenient in that it comes at a time when Rufunsa is finding its feet. In the context of
decentralization, am pleased that a team drawn from all sectors of our district have done a framework that
leaves no one behind in the development agenda.
In the perspective of devolution, the document builds on the tenets of decentralization that demands a
government for, and by the people. We recognise that delivery of inclusive and equitable development to
citizens requires concerted efforts and commitment of all stakeholders, a spirit of teamwork that has been
demonstrated in the compilation of this plan.
With the decentralization process placing more functions on Local Authorities who are responsible for the
direct provision of key services and facilities to the people, the document comes in handy with all
information required for improved service provision, investment opportunities and in the long run,
economic growth.
It has therefore been carefully drawn and has in it all information on the districts’ potential and will act as
a guide to any form of growth that comes with increased demand of services and population growth with
all areas with greatest need captured. With this document in place, I am convinced that through our joint
efforts in the next 10 years, we will be able to achieve the objectives we have set. I have confidence in
Rufunsa’s ability to implement this Plan efficiently and effectively.
Our Cooperating Partners have always been supportive in the development agenda of the district and my
office will continue to appreciate their valuable contributions. I am hopeful that this cooperation will grow
to even greater heights as we implement what we have set for ourselves the plan.
Kennedy Mailoni
Council Chairperson
RUFUNSA TOWN COUNCIL November, 2024
1
--- PAGE 3 ---
ACKNOWLEDGEMENTS
The Integrated Development Plan (IDP) is principally a policy document to
guide development in the District of many cherished stakeholders that
includes the Government Departments, Rufunsa Town Council, Non-
Governmental Organizations, Faith Based Organizations, Agricultural
Cooperative Societies and the Business Community. The purpose of the
Integrated Development Plan (IDP) is to ensure equitable service delivery,
economic development, equitable distribution of infrastructure, spatial
harmony whilst ensuring environmental sustainability.
During the process of developing this document consultations were made in order to have a comprehensive
and inclusive plan in line with status quo in the District. The plan benefited from significant contributions
from stakeholders through various consultative processes at provincial and district level. This was done
to build consensus and ownership.
It is in this regard, that I profoundly wish to thank the District IDP Team, Technical Team, Lusaka
Provincial Administration, Rufunsa District Administration, Rufunsa Town Council, Ward Development
Committees, Provincial Local Government Office and members of the District Development Coordinating
Committee (DDCC); Community Based Organizations, Non-Governmental Organisation (NGO),
Traditional leaders, Cooperating partners and many others.
It must be noted that the contributions by the Local Government Association of Zambia, Commonwealth
Local Government Forum (CLGF) and Ministry of Local Government with financial support made by
European Union (EU) and Foreign and Commonwealth Development Office (FCDO) were of great value
in the preparation of this very important integrated Development Plan for Rufunsa District.
We look forward to continued partnership in search of better and effective avenues for the social-
economic progress of our district and the improved standard of living of our people.
Richard J. Mabena
DISTRICT COMMISSIONE
2
--- PAGE 4 ---
EXECUTIVE SUMMARY
Since its declaration as a district in 2012, Rufunsa District did not have a long
term plan outlining its vision and priorities for development. In 2019 Rufunsa
District commenced preparation of an Integrated Development Plan (IDP) which
is its first ever written long-term plan that expresses its aspirations for the next
10 years with focus on issues arising from stakeholder consultations. Priorities
contained in the document are therefore dynamic and to some extent evolving,
which is what drove the IDP team to adapting its priority list to reflect the actual
and imminent needs of most vulnerable members in communities. The focus is
on key government priorities being, and to be implemented at local level,
description of the existing state of development, issues arising from the public participation process,
impact of changes anticipated over the next ten years and consideration of issues arising relating to Gender
and Vulnerable Groups.
The plan also provides for a Spatial Development Framework which illustrates the physical development
aspirations for the district with an objective of securing land for all sectoral developments within the IDP
area while doubling the supply of land for social and economic service provision. Furthermore, the Spatial
Framework gives direction to future planning and development in the district for purposes of sustainable
economic growth with a plan containing infrastructure development and services to be provided in the
next ten years. This section further provides for development options of which the selected alternative
illustrates the creation and development of satellite towns which will complement the existing township
boundary.
Further, our IDP is envisioned to guide the planned growth of the district which includes the provision of
infrastructure and social services encompassing all the eight sectors while taking into account the existing
conditions, problems, available resources and overall economic and social development for the area. It
sets a framework for how land should be used, what infrastructure and services are needed and how the
environment should be protected in response to community needs and priorities. The implementation of
the plan is cardinal in ensuring that Rufunsa becomes an industrial hub for tourism, mining and agriculture
and this can be achieved through the exploitation and utilisation of natural resources as embedded in our
vision and mission. The full implementation of the laid out projects and programmes will ensure economic
growth, wealth creation, social investment, human development and sustainable socio-economic
development.
When envisioning the year 2033, the outcome is clear, Rufunsa District is well on its way to becoming a
city with extraordinary excellence.
Bishop Venture Kafula PhD
Council Secretary
RUFUNSA TOWN COUNCIL
3
--- PAGE 5 ---
LIST OF ACRONYMS
BCP Bio Carbon Partners
CBO Community Based Organisation
CDF Constituency Development Fund
CLTS Community Led Total Sanitation
CRBs Community Resource Boards
CSO Central Statistical Office
CSOs Civil Society Organisations
DMMU Disaster Management and Mitigation Unit
DNPWL Department of National Parks and Wild Life
ECZ Electoral Commission of Zambia
FHH Female Headed Household
GMA Game Management Area
GRZ Government of the Republic of Zambia
HIVOs Human Institute for Development Cooperation
IDP Integrated Development Plan
LAP Local Area Plan
LED Local Economic Development
LGEF Local Government Equalization Fund
LUP Land Use Plan
MLG Ministry of Local Government
PSIR Planning Surveys and Issues Report
RIDP Rufunsa Integrated Development Plan
RTC Rufunsa Town Council
URP Urban and Regional Planning
WDF Ward Development Fund
ZEMA Zambia Environmental Management Agency
ZREAD Zambia Reading for Education and Development
8NDP Eighth National Development Plan
4
--- PAGE 6 ---
TABLE OF CONTENTS
ACKNOWLEDGEMENTS ........................................................................................................................................ 2
LIST OF ACRONYMS .............................................................................................................................................. 4
PART 1 ..................................................................................................................................................................... 15
INTRODUCTION AND BACKGROUND ............................................................................................................. 15
1 CHAPTER ONE: INTRODUCTION AND BACKGROUND ............................................................................ 16
1.1 Background to Integrated Development Planning (IDP) ................................................................................. 16
1.2 Description of the IDP Area ............................................................................................................................ 16
1. 2.1 Historical Context ................................................................................................................................... 16
1.2.2 Location ...................................................................................................................................... 16
1.2.3 Spatial Extent of the IDP Area ................................................................................................................ 17
1. 3 Topography ................................................................................................................................................... 17
1.4 Climatic Conditions ........................................................................................................................................ 18
1.5 Hydrology and Drainage ................................................................................................................................ 18
1.6 Geology and Soils .......................................................................................................................................... 18
1.7 Natural Vegetation, Forests and Protected Areas .......................................................................................... 18
1.8 Environmentally sensitive areas ..................................................................................................................... 19
PART TWO .............................................................................................................................................................. 20
PLANNING SURVEY AND ISSUES REPORT ..................................................................................................... 20
2 CHAPTER TWO: DEMOGRAPHIC ANALYSIS .............................................................................................. 21
2.1 Population and Population Growth ................................................................................................................. 21
2.2. Population Characteristics ............................................................................................................................. 21
2.2.1 Population Density of Rufunsa District ................................................................................................... 21
2.2.2 Age Distribution and Dependence Ratio ................................................................................................ 22
2.2.2 Gender distribution and Structure of the population ................................................................................ 23
2.2.3 Fertility and Mortality Rates and Life Expectancy .................................................................................. 24
2.2.3 Projected Population and Likely Characteristics ..................................................................................... 26
2.2.4 Mobility and Migration Trends ............................................................................................................... 26
2.3 Projected Population and Likely Characteristics ............................................................................................ 27
5
--- PAGE 7 ---
2.3.1 Demographic and Economic Spatial shifts and Trends ........................................................................... 27
2.3.2 Urbanisation ............................................................................................................................................ 27
2.4 The Impact of the Continuation of Existing Population Trends on Land Use and Spatial Development
Patterns 28
3 CHAPTER THREE: ECONOMIC ANALYSIS .................................................................................................. 29
3.1 Review of Policies and Plans .......................................................................................................................... 29
3.2 Existing Characteristics of the Economy ......................................................................................................... 29
3.2.1 Employment and Unemployment Labor Analysis ................................................................................... 29
3.2.2 Poverty Levels ......................................................................................................................................... 30
3.2.3 Characteristics of business environment ................................................................................................... 30
3.2.4 Main Constraints to Local Business Development .................................................................................. 31
3.2.5 Existing Economic Activities and Investment Potential ........................................................................... 32
3.2.6 Summary ...................................................................................................................................... 34
CHAPTER FOUR: TRANSPORT AND COMMUNICATION ............................................................................. 36
4.1 Review of Policies and Plans ......................................................................................................................... 36
4.2 Description of the Existing State of Development ......................................................................................... 36
4.2.1 Availability of Service ............................................................................................................................. 36
4.2.2 Quality of Service Including Key Indicators of Performance ................................................................... 37
4.3. Issues arising from the Public Participation Process ..................................................................................... 40
4.4 Impact of Changes Anticipated Over the Next Ten Years ............................................................................. 41
4.4.1. Population Change – Future Demand for Services and Facilities ........................................................... 41
4.4.2. Existing and Proposed Investment and Development Programmes........................................................ 41
4.5 The Impact of the Continuation of Existing Trends on Land Use and Population Distribution Patterns ........ 41
4.6 Environment and Climate Change Analysis .................................................................................................... 42
4.6.1 The Impact of Existing Trends on the Environment and Climate Change .............................................. 42
4.6.2 The Impact of Environmental and Climate Change Issues on the Sector ................................................ 42
4.7 Issues Arising Relating to Gender Groups and Vulnerable Groups ............................................................... 43
4.8 Consideration of the Underlying Factors Contributing To the Issues Identified ............................................ 43
4.9 Summary ........................................................................................................................................................ 43
6
--- PAGE 8 ---
5 CHAPTER FIVE: HEALTH ............................................................................................................................... 44
5.1 Review of Policies and Plans .......................................................................................................................... 44
5.2. Description of the Existing State of Development ......................................................................................... 44
5.2.1. Availability of the service ....................................................................................................................... 44
5.2.2 Quality of the Service Including Key Indicators of Performance ............................................................ 45
5.3. Issues arising from the Public participation Process ...................................................................................... 45
5.4. Impact of Changes Anticipated Over the Next Ten Years ............................................................................ 46
5.4.1 Population Change – Future Demand for Services and Facilities ............................................................ 46
5.4.2 Existing and Proposed Investment and Development Programmes ........................................................ 46
5.5 The Impact of the Continuation of Existing Trends on Land Use and Population Distribution Patterns ........ 46
5.6 Environment and Climate Change Analysis ................................................................................................... 47
5.6.1 The Impact of Existing Trends on the Environment and Climate Change ............................................... 47
5.6.2 The Impact of Environmental and Climate Change Issues on the Sector ................................................. 47
5.7 Issues arising relating to gender groups and vulnerable groups ..................................................................... 47
5.8 Consideration of the underlying factors contributing to issues identified ....................................................... 47
5.9 Summary ........................................................................................................................................................ 47
6 CHAPTER SIX: EDUCATION ........................................................................................................................... 48
6.1 Review of Policies and Plans .......................................................................................................................... 48
6.2 Description of the Existing State Of Development .......................................................................................... 48
6.2.1 Availability of Service .............................................................................................................................. 48
6.2.2 Quality of Service Including Key Indicators of Performance ................................................................... 49

In [45]:
tables = []

with pdfplumber.open(bursary_path) as pdf:

    for page_number, page in enumerate(
        pdf.pages,
        start=1
    ):

        page_tables = page.extract_tables()

        for table in page_tables:

            df_table = pd.DataFrame(table)

            df_table["source_page"] = page_number

            tables.append(df_table)

Standardizing

In [51]:
import pandas as pd

cdf_links = pd.read_csv(
    "../data/raw/rufunsa_cdf_links.csv",
    sep="|"
)

bursary_links = cdf_links[
    cdf_links["title"].str.contains(
        "BURSARY|BURSARIES",
        case=False,
        na=False
    )
]

display(bursary_links[["title", "url"]])

Empty DataFrame
Columns: [title, url]
Index: []

In [52]:
df = pd.concat(all_tables, ignore_index=True)

print(df.shape)
display(df.head())

df.columns = (
    df.columns
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("-", "_", regex=False)
)

# Remove empty rows/columns:
df = df.dropna(how="all")
df = df.dropna(axis=1, how="all")

# Remove duplicates:

print(
    "Duplicates:",
    df.duplicated().sum()
)
df = df.drop_duplicates()

df["council"] = "Rufunsa Town Council"
df["province"] = "Lusaka Province"
df["district"] = "Rufunsa"
df["constituency"] = "Rufunsa"
df["financial_year"] = 2025

df["programme_type"] = "Empowerment Grant"

df["source_url"] = bursary_url
df["source_document"] = "2025 Approved Secondary School Bursaries"

df["retrieval_date"] = (
    pd.Timestamp.today().strftime("%Y-%m-%d")
)

df["record_id"] = [
    f"RUF-BE-{i:04d}"
    for i in range(1, len(df) + 1)
]

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing:")
print(df.isna().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

(2324, 12)

,0,1,2,3,4,5,6,7,8,source_page,9,10
0,2010 Population,NaN,NaN,2022 Population,NaN,NaN,Average Annual Population\nGrowth Rate 2010- 2022,NaN,NaN,22,NaN,NaN
1,Male,Female,Total,Male,Female,Total,Male,Female,Total,22,NaN,NaN
2,"25,785","25,217","51,002","41,478","40,255","81,733",4.0,4.0,4.0,22,NaN,NaN
3,Population,Land Area,Population Density (Pop/Land\nArea),NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
4,"82,347","9,446.0",8.7,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN

Duplicates: 287

NameError: name 'bursary_url' is not defined

Export

In [ ]:
output = (
    "../data/cleaned/"
    "db-unza26-csc4792-rufunsa_cdf_bursaries_empowerment.csv"
)

df.to_csv(
    output,
    sep="|",
    index=False
)

print("Saved:", output)

## IDP Projects Dataset
A. Main source
Use the Rufunsa Integrated Development Plan:
C. Target columns
* record_id
* council
* province
* district
* constituency
* ward
* project_name
* sector
* project_description
* implementation_period
* project_status
* estimated_cost
* source_url
* source_document
* retrieval_date

D. Download the IDP

In [17]:
import requests

idp_url = (
    "https://www.rufunsacouncil.gov.zm/"
    "wp-content/uploads/2025/11/"
    "RUFUNSA_IDP_2024-April2025-1-2-1.pdf"
)

response = requests.get(
    idp_url,
    verify=False,
    timeout=30
)

print(response.status_code)
print(response.headers.get("Content-Type"))

C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.rufunsacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
application/pdf

In [19]:
idp_path = (
    "../data/raw/"
    "rufunsa_idp.pdf"
)

with open(idp_path, "wb") as file:
    file.write(response.content)

In [20]:
!pip install pdfplumber

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pdfplumber in C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages (from pdfplumber) (5.13.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from pdfminer.six==20260107->pdfplumber) (49.0.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\IMMANUEL\AppData\Roaming\Python\Python314\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)

In [21]:
import pdfplumber

with pdfplumber.open(idp_path) as pdf:

    print(
        "Pages:",
        len(pdf.pages)
    )

Pages: 197

In [22]:
idp_text = ""

with pdfplumber.open(idp_path) as pdf:

    for page_number, page in enumerate(
        pdf.pages,
        start=1
    ):

        text = page.extract_text()

        if text:

            idp_text += (
                f"\n--- PAGE {page_number} ---\n"
            )

            idp_text += text

In [23]:
keywords = [
    "project",
    "development",
    "education",
    "health",
    "water",
    "sanitation",
    "road"
]

for keyword in keywords:

    print(
        keyword,
        idp_text.lower().count(keyword)
    )

project 146
development 392
education 73
health 165
water 235
sanitation 52
road 124

In [24]:
all_tables = []

with pdfplumber.open(idp_path) as pdf:

    for page_number, page in enumerate(
        pdf.pages,
        start=1
    ):

        tables = page.extract_tables()

        for table in tables:

            if table:

                df_table = pd.DataFrame(table)

                df_table["source_page"] = (
                    page_number
                )

                all_tables.append(df_table)

print(
    "Tables found:",
    len(all_tables)
)

Tables found: 138

In [25]:
for i, table in enumerate(all_tables):

    print("TABLE:", i)

    display(table.head(10))

TABLE: 0

,0,1,2,3,4,5,6,7,8,source_page
0,2010 Population,NaN,NaN,2022 Population,NaN,NaN,Average Annual Population\nGrowth Rate 2010- 2022,NaN,NaN,22
1,Male,Female,Total,Male,Female,Total,Male,Female,Total,22
2,"25,785","25,217","51,002","41,478","40,255","81,733",4.0,4.0,4.0,22

TABLE: 1

            0          1                                    2  source_page
0  Population  Land Area  Population Density (Pop/Land\nArea)           23
1      82,347    9,446.0                                  8.7           23

TABLE: 2

           0       1  source_page
0  Age Group   Total           23
1        0-9  16,619           23
2      10-19  13,455           23
3      20-29   7,144           23
4      30-39   5,029           23
5      40-49   3,234           23
6      50-59   2,227           23
7       60 +   3,294           23

TABLE: 3

                          0     1     2     3  source_page
0               Rural/Urban  1990  2000  2010           24
1    Child Dependency Ratio  80.4  76.7  69.7           24
2     Aged Dependency Ratio     2   2.6   2.8           24
3  Overall Dependency Ratio  82.4  79.3  72.5           24

TABLE: 4

,0,1,2,3,4,5,6,source_page
0,Category,2017,2018,2019,2020,2021,2022,24
1,Total Male (no.),32509,33984,"35,396",36441,"39,456","41,807",24
2,Total Female\n(no.),33139,34643,"34,008",35011,"37,909","40,540",24
3,Total\nPopulation,65648,68627,"69,404","71,452","77,365","82,347",24

TABLE: 5

     0            1       2      3       4  source_page
0  S/N         WARD   TOTAL   MALE  FEMALE           25
1    1  Bunda-bunda  12,063  6,176   5,887           25
2    2    Nyangwena   8,206  4,141   4,065           25
3    3       Kabuyu   3,669  1,848   1,821           25
4    4   Mwachilele   3,185  1,610   1,575           25
5    5    Namanongo   5,139  2,669   2,470           25
6    6   Chintimbwi   7,045  3,380   3,665           25
7    7      Rufunsa   9,930  4,910   4,065           25
8    8    Shikabeta   2,119  1,077   1,042           25
9    9     Kankumba   8,833  4,544   4,289           25

TABLE: 6

,0,1,2,3,4,source_page
0,Category,percent,2017,2018,2019,25
1,Children 0 –\n11 Months,3.70\npercent,2417,2539,2765,25
2,12-59 Months,12.90\npercent,8507,8853,11058,25
3,5+ Years,87.90\npercent,57705,60323,60752,25
4,Women 15 –\n49 Years\n(WCBA),26.50\npercent,17401,18529,18661,25
5,Total Male,49.50\npercent,32509,33984,"35,396",25
6,Total Female,50.50\npercent,33139,34643,"34,008",25
7,,,,,,25

TABLE: 7

                       0              1     2     3     4  source_page
0  Expected\nPregnancies  5.40\npercent  3545  3706  3732           26
1   Expected\nDeliveries  5.20\npercent  3324  3569  3594           26
2  Expected\nLive Births  4.95\npercent  3196  3431  3421           26

TABLE: 8

     0            1                 2      3       4  source_page
0  No.         Ward  Total Population    NaN     NaN           26
1                               Total   Male  Female           26
2    1  Bunda-bunda            12,063  6,176   5,887           26
3    2    Nyangwena             8,206  4,141   4,065           26
4    3       Kabuyu             3,669  1,848   1,821           26
5    4   Mwachilele             3,185  1,610   1,575           26
6    5    Namanongo             5,139  2,669   2,470           26
7    6   Chintimbwi             7,045  3,380   3,665           26
8    7      Rufunsa             9,930  4,910   4,065           26
9    9    Shikabeta             2,119  1,077   1,042           26

TABLE: 9

      0           1  source_page
0  YEAR  POPULATION           27
1  2020       71452           27
2  2025       81677           27
3  2030       91902           27
4  2040      112352           27

TABLE: 10

,0,1,2,3,4,5,6,7,8,9,source_page
0,District,2010 (Before splitting),NaN,NaN,2010 (After splitting),NaN,NaN,2020,NaN,NaN,27
1,NaN,Total,Male,Femal\ne,Total,Male,Femal\ne,Total,Male,Female,27
2,Chongw\ne,"192,30\n3","96,685","95,618","141,30\n1","70,90\n0","70,40\n1","229,90\n1","115,41\n0","114,49\n1",27
3,Kafue,"227,46\n6","113,91\n0",11355\n6,"120,41\n5","60,04\n7","60,36\n8","183,99\n5","91,814","92,181",27
4,Rufunsa,N/a,N/a,N/a,"51,002","25,78\n5","25,21\n7","71,452",36155,"35,297",27

TABLE: 11

,0,1,2,3,source_page
0,,Total,Male,Female,30
1,Total Population,"51,002","25,785","25,217",30
2,Working age population 20 years or older,"17,634","8,834","8,800",30

TABLE: 12

,0,1,2,3,source_page
0,Rufunsa Labour Force,"17,634","8,834","8,800",31
1,Sector of employment,NaN,NaN,NaN,31
2,Formal,1184,655,529,31
3,Informal,188,154,34,31
4,Total Employed Persons,"1,372",809,563,31
5,Labour force participation rate,7.8 percent,9.1 percent,6.4 percent,31
6,Unemployed population,"16,262","8,200","8,062",31
7,Unemployment Rate,92.2 percent,92.8 percent,91.6 percent,31
8,Youth Population,"12,173","6,087","6,086",31

TABLE: 13

,0,1,2,3,source_page
0,S/N WARD NUMBER OF POOR TOTAL\nPOPULATION,NaN,NaN,NaN,31
1,1,Mwachilele,"3,414",8900,31
2,2,Nyangwena,"5,946",5628,31
3,3,Bunda-Bunda,"11,309",10588,31
4,4,Nyamanongo,"2,522",4717,31
5,5,Rufunsa,"12,827",15133,31
6,6,Mankanda,"3,081",7268,31
7,7,Shikabeta,"1,599",2341,31
8,,TOTAL,"40,698",,31

TABLE: 14

,0,1,2,source_page
0,S/N,ROAD\nNAME,EXISTING STATUS,38
1,1,Munyeta,"Munyeta area “the food basket” is located in Kabuyu Ward where\nfarming is main economic stay, hence a proper road network to connect\nsuch a productive area becomes paramount. The road has only three (3)\nmajor crossing points and becomes impassable during the rainy season.\nThis makes it difficult for farmers to transport their produce and the\ncommunity to access social services such as schools, clinics, police posts.",38
2,2,Chomba,The road is located on the North-Eastern part of the district in Shikabeta\nWard and is only passable during dry season. It has fourteen (14) crossing\npoints with no culverts or bridges installed,38
3,3,Shikabeta,"This area is located on the Northern part of the district. The road has a\npoor section approximately 50 meters off the great east road, leaving it\nimpassable and poses a challenge to access other areas such as Chomba\nas well as Lubalashi.",38
4,4,Shimunguwo,Shimunguwo is located on the eastern part of the district along the banks\nof Luangwa River in Mankhanda Ward. During rainy season the\ncommunity relies on water transport to access most social services as the\nroads become so impassable.,38
5,5,Chipeketi,Chipeketi area in Chintimbwi Ward has a poor road network and is\nunmotorable during the rainy season resulting in communities covering\nover 22km to access health service. The Road lacks and some crossing\npoints have poor culverts/bridges.,38
6,6,Kamwesha,Kamwesha area located within Chintimbwi Ward has a poor road\nnetwork which worsens during rainy season. This inhibits the provision\nof adequate social services such as water supply.,38
7,7,Chintili,Chintili in Kankumba Ward has a poor road network during the rainy\nseason thus posing a challenge for the community to access social\nservices,38

TABLE: 15

,0,1,2,3,4,5,source_page
0,Chipeketi,22,Gravel,Motorable,Chitimbwi,"Ng'ombe,",39
1,,,,,,"Chapopa,",39
2,NaN,NaN,NaN,NaN,NaN,"Mbuyakaluba,",39
3,NaN,NaN,NaN,NaN,NaN,"Noashi,",39
4,NaN,NaN,NaN,NaN,NaN,Kamanuma,39
5,Kamwesha,12,Gravel,Non motorable\nduring rainy season,Chitimbwi,"Shimwapona\n1,2 &3,\nPokelela,\nChikwenya,\nMkumbatwemb\ne",39
6,Shimungu’b,11,Gravel,Non motorable,Mankanda,"Ngongo,",39
7,o,,,during rainy season,,"Chaziche,",39
8,,NaN,NaN,,NaN,"Mkunkhu,",39
9,NaN,NaN,NaN,NaN,NaN,Shimuguwo,39

TABLE: 16

,0,1,2,3,4,source_page
0,Proposed Road\nNames,Description,Road\nType,Status,Total\nKm,40
1,Tulalumbu road,T4-Kalubangwe Road,Gravel,Motora\nble,1.3,40
2,Kalubangwe road,T4 Junction - T4(DC’s houses),Gravel,Motora\nble,6.1,40
3,Chintibwi road,Kalubangwe (Zesco houses - Mission\nHospital),Gravel,Motora\nble,10,40
4,Unnamed road,"DC,s houses - Government houses",Gravel,Motora\nble,0.2,40
5,Unnamed road,Civic center -Chintimbwi Rd,Gravel,Motora\nble,0.6,40
6,Unnamed road,Chintimbwi - DC’s Offices,Gravel,Motora\nble,0.4,40

TABLE: 17

,0,1,source_page
0,S/N,EXISTING DEVELOPMENT PROGRAMS,42
1,1,Completion of a Post Office,42
2,2,"Rehabilitation of feeder roads: Chipeketi, Munyeta, Chakwenga and\nRUTEC road.",42
3,3,Rehabilitation of culverts and bridges (Shikabeta bridge and Mulamba\nculverts),42
4,4,Erection of mobile network towers,42

TABLE: 18

,0,1,source_page
0,S/N,PROPOSED DEVELOPMENT PROGRAMS,42
1,1,Establishment of the community Radio station,42
2,3,Upgrading of feeder and Township roads to bituminous standard,42
3,4,Installation of mobile network towers and extension of radio coverage,42
4,5,Installation of overhead and underground fiber network,42
5,6,Construction of Truck Parking Bay,42
6,7,Linking of the Great East road and the Great North road through the\nShikabeta road,42
7,8,"Rehabilitation of feeder road: Chaola, Chiyota, Shimunguwo,\nMweshang’ombe, Kashimpa and Kamwesha roads.",42

TABLE: 19

     0                                      1            2  source_page
0  S/N                 FACILITY TYPE AND NAME         WARD           45
1    1  Maternity Wing at Munyeta Health Post       Kabuyu           45
2    2                  Mwambashi Health Post     Kankumba           45
3    3                   Kashimpa Health Post  Bunda-Bunda           45
4    4                 Shimunguwo Health Post     Mankanda           45

TABLE: 20

,0,1,2,3,4,5,6,source_page
0,Category,2021,,2022,,2023,,46
1,NaN,Number,%,Number,%,Number,%,46
2,,NaN,NaN,NaN,NaN,NaN,NaN,46
3,Children 0 – 11\nMonths,3105,4,3217,4,3333,4,46
4,<5 Years,15527,20,16086,20,16665,20,46
5,5 – 14\nYears,19409,25,20108,25,20831,25,46
6,Women 15 – 49\nYear,20961,27,21716,27,22497,27,46
7,All Adults 15\nYears+,45805,59,47454,59,49161,59,46
8,Total Male (All\nages),37575,48.4,38928,48.4,40329,48.4,46
9,Total Female (All\nages),40060,51.6,41502,51.6,42995,51.6,46

TABLE: 21

   0                        1       2  source_page
0           SCHOOL CATEGORIES  NUMBER           49
1  1                Secondary      13           49
2  2                  Primary      54           49
3  3                Community      13           49
4  4            Skills Centre      03           49
5  5                  Private      04           49
6  6  University (Ambassador)      01           49
7                       TOTAL      88           49

TABLE: 22

       0                          1     2       3      4  source_page
0    S/N                      LEVEL  MALE  FEMALE  TOTAL           50
1      1  Early Childhood Education    01      12     13           50
2      2                    Primary   111     131    242           50
3      3                  Secondary    75      40    115           50
4  TOTAL                        NaN   187     183    370           50

TABLE: 23

,0,1,source_page
0,Where Water is accessed,No. of Household,62
1,District: Rufunsa,11689,62
2,Piped water inside the dwelling,73,62
3,Piped water inside the yard,36,62
4,Piped water from access point outside the yard,21,62
5,Borehole,11326,62
6,Spring,39,62
7,Dam/pool,0,62
8,River/stream,194,62
9,Rain water tank,0,62

TABLE: 24

,0,1,2,3,4,source_page
0,S./No,Name of the ward,Population,Total number of,Number of,62
1,,,,existing boreholes,Boreholes,62
2,NaN,NaN,NaN,in the ward,Required,62
3,1,Rufunsa,16742,44,38,62
4,2,Chintimbwi,4661,25,11,62
5,3,Mankhanda,4042,27,17,62
6,4,Mulamba,"9,926",22,10,62
7,4,Shikabeta,2954,26,7,62
8,5,Kankumba,5826,60,9,62
9,6,Bunda Bunda,15305,179,30,62

TABLE: 25

,0,1,2,3,4,5,source_page
0,Block,Name of,Number,Male,Female,No of,73
1,Name,camp,of Zones,Farmers,Farmers,farmers,73
2,,,,,,serviced,73
3,Rufunsa,Lukwipa,8,677,385,"1,062",73
4,,Shikabeta,8,329,161,490,73
5,NaN,Mpanshya,8,452,275,727,73
6,NaN,Rufunsa Central,8,345,225,570,73
7,NaN,Chimusanya,10,"1,347","1,001","2,348",73
8,Bunda-Bunda,Sinjela,9,"1,546",795,"2,341",73
9,,Chinyunyu,8,"1,480",838,"2,318",73

TABLE: 26

,0,1,2,3,source_page
0,S/N,Service,KPI,Number of Beneficiaries.,75
1,01,Extension\nServices,Number of farmers accessing extension\nservices,"15,700",75
2,02,Farmer Inputs,Number of farmers accessing farmer,"12,142",75
3,03,irrigation\nschemes,Number of farmers accessing irrigation\nschemes,200 households to be\ntargeted for the two\nirrigation schemes.,75
4,04,Fish Farming,Number of targeted beneficiaries.,,75

TABLE: 27

,0,1,2,3,4,source_page
0,S/N,NAME OF\nORGANISATION,SERVICES.,AREAS OF\nCONSERVATION,PERFORMANCE\nINDICATORS,78
1,01,Forest Department.,-Forest\nprotection and\nmanagement\n-forest\nextension and\npublicity\n- nursery\nmanagement/\nwoodlot\nestablishment\n-beekeeping\ntechnology\ndevelopment\n-formation of\ncommunity\nforest\nmanagement\ngroups\n-licensing of\nforest products,"Munyeta forest\nreserve No. 399, and\nthe entire District in\ncollaboration with\npartners.",-Number of forest patrols\nconducted\n-Number of sensitisation\nmeetings conducted\nNumber of\nwoodlot/plantation\nestablished\nNumber of beekeeping\ntrainings conducted\nNumber of community\nForest Management\nGroups formed\nAmount of revenue\nraised,78

TABLE: 28

,0,1,2,3,4,source_page
0,02,CRB,"Patrols,\nSensitization\nProviding\nagriculture",All designated\nconservation areas\nin the three\nchiefdoms of the\ndistrict, Number of forest\nfires curbed\n Hectarage of\nconversation areas\n Number of Gama\nrangers engaged,79
1,03,Bio - Carbon\nPartners,Designation of\nForest\nConservation\nSupporting\nCRB’s,Bunda bunda 4\nzones," 40,126 Hectares has\nbeen Conserved in\nBundabunda\n Approximately\n97,000 hectares in\nMpashya\n In Shikabeta 101,348\nhectors of land has\nbeen conserved",79
2,04,National Parks and\nWildlife.,"Sensitization on\nwild life\nconservation,\nSupport CRB","Lower Zambezi,\nLuano GMA","Number of Patrols in the\nLower Zambezi, and the\nLuano and Rufunsa\nGMA",79
3,05,SCRALA,Support climate\nresilient\nagricultural\npractices.,The entire District,,79

TABLE: 29

,0,1,2,source_page
0,S/N,NAME OF\nORGANISATION,KEY INDICATORS OF PERFORMANCE IN 2026,80
1,1,Forestry department\nRufunsa.,"Protection and management 2022-2026\n-80 forest and high way patrols to be conducted\nForest extension sensitisation meetings\n-60 sensitization meetings held\nNursery management / seedling production\n250,000 seedlings raised\nBeekeeping trainings\n-24 trainings to be conducted\nCommunity forest management groups formation",80

TABLE: 30

,0,1,2,source_page
0,,,"-5 community forest management groups\nLicencing / raise revenue\nK3.500,000 raised",81
1,2,Bio-Carbon Partners,"By 2020 a total of 238,474 hectors of land in the district had been\nconserved",81

TABLE: 31

,0,1,2,source_page
0,S/N,Name Of Organisation,Proposed Investment And Development Programmes.,81
1,1,CRB,Protection of Forests and Game Management Areas,81
2,2,Forest Department,-Plantation/ woodlot establishment\n-Nursery establishment and management (seedling raising)\n-Processing of honey and honey products\n-Value addition to non-timber forest products\n-Establishment of a sawmilling plant\n-Formulation of community forest management groups\n-Community sensitization meetings\n-Training of beekeepers,81
3,NaN,NaN,Forest patrols,81

TABLE: 32

,0,1,2,source_page
0,3,Bio-Carbon Partners,REDD Plus 30 years,82
1,NaN,NaN,Cash Dividends,82
2,4,Wildlife and National\nParks,Preparation of Game Management Plans for all Protected\nareas,82

TABLE: 33

,0,1,2,source_page
0,"VISION\n“ An industrial hub for tourism, mining and agriculture through sustainable exploitation\nof natural resources in Lusaka province by the year 2034”",NaN,NaN,86
1,Economic Growth,Social Investment,Sustainable,86
2,and Wealth Creation,and Human Development,Socio-Economic,86
3,,,Development,86
4,MISSION\nTo strive to be the leading community driven district in the provision of sustainable\nservices and developmental Programs,NaN,NaN,86

TABLE: 34

,0,1,source_page
0,Policy Instrument,Description of the Effect of Policies on Rufunsa’s Development,86
1,Vision 2030:,Aims to make Zambia a more developed middle-income society.,86
2,Land Act (1995),"All land is vested on H.E. the President of Zambia, the continuation of",86
3,,leasehold tenure to individuals or private entities is ensured. The Act,86
4,NaN,"provides for the statutory recognition of customary tenure, with",86
5,NaN,possibility of being converted to private land. It also establishes the land,86
6,NaN,development fund and land tribunals.,86
7,8th National,Provide a national framework for resources allocation every 5 years.,86
8,Development Plans,,86
9,"(NDPs),",NaN,86

TABLE: 35

,0,1,source_page
0,,"results are identification of urban development priorities, guidance on the",87
1,,"future development priorities, better coordination and guidance of",87
2,NaN,actions and increased and more coordinated investment priorities.,87
3,Zambia Wildlife,Makes provision for the management and conservation of wildlife in,87
4,Act (2015),Zambia. Further provides for trade in wild animals and meat of wild,87
5,,animals. It also provides for the development and implementation of,87
6,NaN,management plans;,87
7,National Parks and,undertakes to unlock the economic potential of the sector for the benefit,87
8,Wildlife Policy,of present and future generations and to secure it from various threats.it,87
9,(2018),provides guidance on enhancing biodiversity conservation and,87

TABLE: 36

,0,1,2,source_page
0,S/N,IDP GOALS,STRATEGIC OBJECTIVES,87
1,1,To transform the Local\nEconomy of Rufunsa and\nCreate Jobs,To enhance the Farmer support Programmes,87
2,NaN,NaN,To promote cooperative development,87
3,NaN,NaN,To develop and maintain road infrastructure,87
4,NaN,NaN,To establish public transport infrastructure,87
5,NaN,NaN,To Enhance Tourism Diversification,87
6,NaN,NaN,To promote Local Economic Development,87
7,NaN,NaN,To Enhance Revenue collection,87
8,2.,To enhance human and social\ndevelopment,To improve access to education for all leaners,87
9,NaN,NaN,To improve health and wellbeing of residents in the\ndistrict,87

TABLE: 37

,0,1,2,3,4,5,6,7,8,source_page
0,Objective,Farmer Support Programme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88
1,Strategy,to promote diversification within the agriculture sector by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88
2,Programme,Activities,Location (by,Target,Target,Target,Target,Target,Responsible,88
3,,,priority),Year 1,Year 2,Year 3,Year 4,Year 5,Agency/,88
4,NaN,NaN,,,,,,,Officer,88
5,Infrastructure,Setting up of livestock and\nfisheries service centers,"Nyamphande,\nMunyeta,\nChakwenga,\nChinzete,\nMwambashi",,1,1,1,1,DFLCO,88
6,Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88
8,NaN,Setting up of breeding\ncenters,"Chinyunyu,\nMwachilele,\nNamanongo",,,1,1,,DFLCO,88
9,NaN,Setting up of fish\nhatcheries,Lukwipa and\nKanyongoloka,,,,1,,DFLCO,88

TABLE: 38

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89
2,NaN,Construction of Dip Tanks,"Rufunsa,\nMpanshya,\nSinjela,\nKabuyu,\nMunyeta,\nNamanongo,\nKanyongoloka",,2,2,2,2,MFL,89
3,Infrastructure,Construction of office\nblock,Rufunsa,,1,,,,MFL/MOA,89
4,Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89
5,,Construction of Staff\nHouses,"Mpanshya,\nRufunsa,\nNdubulula,\nNamanongo",,,1,1,1,MFL/MOA,89
6,NaN,Rehabilition of Staff\nHouses,"Nkalamabwe,\nChiyota,\nChinyunyu,\nMwachilele,\nLukwipa",,1,1,1,1,MFL/MOA,89
7,Extension services,Farmer trainings,"5 camps\n(Mpanshya,\nRufunsa,\nChinyunyu,\nNangwena and\nSinjela","1,800",2250,2800,3500,"4,300",DFLCO,89
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89
9,Crop,Farmer Registration,Agricultural\nCamps,1800,1800,1800,1800,1800,DACO,89

TABLE: 39

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90
2,NaN,Promotion of farm\nManagement Skills,Agricultural\nCamps,2000,2000,2000,2000,2000,DACO,90
3,NaN,Nutritional Education,Agricultural\nCamps,510,510,510,510,510,DACO Partners,90
4,NaN,Extension Methodology -\nTrainings,Agricultural\nCamps,19,20,21,22,23,DACO,90
5,NaN,Extension Methodology -\nFarner field schools,Agricultural\nCamps,"1,020","1,020","1,020","1,020","1,020",DACO,90
6,Sensitization on,Agricultural News and\nLiterature Production/\nRadio Farm Forum,Agricultural\nCamps,5,4,5,4,4,DACO Partners,90
7,access to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90
8,"agricultural ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90
9,information and,Provincial and District\nshows,Rufunsa\nDistrict,2,2,2,2,2,MOA/Partners,90

TABLE: 40

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91
2,NaN,training of farmers in\nfarmer managed natural\nregeneration [FMNR],District,800,800,1000,1500,3000,MFL/MWDSE,91
3,NaN,Training farmers in\nMarketing of livestock,District,1000,1500,2500,3500,3500,Livestock\nDepartment,91
4,Agriculture Land,Creation of Rufunsa\nFarming Block,District,"10,000","10,000","10,000","10,000","10,000",DACO/MLG/M\nOLNR,91
5,Empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91
6,Organic Farming,"Trainings, Demonstration\nand Food Fares","Mwachilelele,\nNyangwena\nand Sinjela",1,1,1,1,1,Kasis\nAgriculture\nTraining Centre\n(KATC),91
7,Promotion and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91
8,Natural Soil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91
9,Enhancement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91

TABLE: 41

,0,1,2,3,4,5,6,7,8,source_page
0,Strategy,"Develop appropriate irrigation, land and water management systems",NaN,NaN,NaN,NaN,NaN,NaN,NaN,92
1,Programme,Activities,Location (by,Target,Target,Target,Target,Target,Responsible,92
2,,,priority),Year 1,Year 2,Year 3,Year 4,Year 5,Agency/,92
3,NaN,NaN,,,,,,,Officer,92
4,"Agricultural Crop\nProduction,\nAdvisory Services\nand Technical\nServices",Irrigation,Rufunsa,6,6,6,6,6,DACO,92
5,NaN,Advisory services,Rufunsa,68,68,68,68,68,DACO,92
6,NaN,Crop Production,Rufunsa,17,17,17,17,17,DACO,92
7,Objective,The Local Authority to establish a well-defined public transportation system by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92
8,Strategy,Construct public transportation facilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92
9,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92

TABLE: 42

,0,1,2,3,4,5,6,7,8,source_page
0,Strategy,promote diversification of tourism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93
1,Programme,Activities,Location (by,Target,Target,Target,Target,Target,Responsible,93
2,,,priority),Year 1,Year 2,Year 3,Year 4,Year 5,Agency,93
3,"Sports, Arts and",Construction of District\nCultural Centre,District,,,1,,,Culture\nDepartment,93
4,Culture Promotion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93
5,,Promotion of cultural\ndiversity programmes,District,2,2,2,2,2,Culture\nDepartment,93
6,NaN,Conduct festivals and\nexhibition of artifacts,District,7,7,7,7,7,Culture\nDepartment,93
7,NaN,Promote traditional\nceremonies,District,3,3,3,3,3,Culture\nDepartment,93
8,NaN,Advertise the local cultural\nhistory in varied media\nplatforms,National,3,3,3,3,3,Culture\nDepartment,93
9,Objective,To promote peri-urban and rural economies by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93

TABLE: 43

,0,1,2,3,4,5,6,7,8,source_page
0,Programme,Activities,Location (by,Target,Target,Target,Target,Target,Responsible,94
1,,,priority),Year 1,Year 2,Year 3,Year 4,Year 5,Agency,94
2,Revenue,Preparation and\nenforcement of the\nvaluation roll,District,,,1,1,,LA,94
3,enhancement and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94
4,diversification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94
5,,Construction of truck park\nin Bay,Rufunsa\nTownship,1,,1,1,,LA,94
6,NaN,Construction of an\nEngineering Depot,Rufunsa\nTownship,,,1,1,1,LA,94
7,NaN,Setting up of Block\nmaking plant,Rufunsa\nTownship,,,1,1,,LA,94
8,NaN,Setting up of a metal\nfabrication workshop,Rufunsa\nTownship,,,1,1,,LA,94
9,NaN,Rehabilitation &\nConstruction of Lodges,Luangwa\nShikabeta,1,1,1,,,LA,94

TABLE: 44

,0,1,2,3,4,5,6,7,8,9,source_page
0,Strategy,Construct public transportation facilities by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95
1,Programme,Activities,Implemen,Source,Cost per year,NaN,NaN,NaN,NaN,Total,95
2,NaN,NaN,ting,NaN,Year 1,Year 2,Year 3,Year 4,Year 5,,95
3,NaN,NaN,NaN,of fund,NaN,NaN,NaN,NaN,NaN,NaN,95
4,,,agency,NaN,NaN,NaN,NaN,NaN,NaN,,95
5,NaN,NaN,NaN,,,,,,,NaN,95
6,Infrastructu\nre\nDevelopment,Construction\nof Bus\nStations,LA,LGEF/L\nR,-,-,-,"638,378","638,378","1,276,756.00",95
7,NaN,Construction\nof Bus stops,LA,LGEF/L\nR,-,"57,100","57,100","57,100","57,100","228,400.00",95
8,NaN,Securing\nLand for an\nAirstrip,LA/NACL,LA,,,"5,000",-,-,"5,000.00",95
9,"Road\nInfrastructu\nre\nMaintenance\n,\nRehabilitatio\nn and\nUpgrading",Periodic\nmaintenance\non District\nfeeder roads,LA,MLGRD\n/RDA,"91,000,00\n0","150,000","300,000","131,303,627","148,373,09\n9","371,126,726.0\n0",95

TABLE: 45

,0,1,2,3,4,5,6,7,8,9,source_page
0,,,Implemen,Source,Year 1,Year 2,Year 3,Year 4,Year 5,,96
1,,,ting,NaN,NaN,NaN,NaN,NaN,NaN,,96
2,NaN,NaN,NaN,of fund,NaN,NaN,NaN,NaN,NaN,NaN,96
3,NaN,NaN,agency,NaN,,,,,,NaN,96
4,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,96
5,"Sports, Arts\nand Culture\nPromotion",Construction\nof District\nCultural\nCentre,Culture\nDepartmen\nt,GRZ/\nPartners,0,0,"1,099,000",0,0,"1,099,000.00",96
6,NaN,Promotion\nof cultural\ndiversity\nprogrammes,Culture\nDepartmen\nt,GRZ/\nPartners,"5,750","6,613","7,604","8,745","5,000","33,711.91",96
7,NaN,Conduct\nfestivals and\nexhibition of\nartifacts,Culture\nDepartmen\nt,GRZ/\nPartners,"3,450","3,968","4,563","5,247","6,034","23,261.22",96
8,NaN,Promote\ntraditional\nceremonies,Culture\nDepartmen\nt,GRZ/\nPartners,"2,588","2,976","3,422","3,935","4,526","17,445.91",96
9,NaN,Arts and\nCulture\nCooperative\ndevelopment,Culture\nDepartmen\nt,GRZ/\nPartners,"11,500","13,225","15,209","17,490","20,114","77,537.38",96

TABLE: 46

,0,1,2,3,4,5,6,7,8,9,source_page
0,,,Implemen,Source,Year 1,Year 2,Year 3,Year 4,Year 5,,97
1,,,ting,NaN,NaN,NaN,NaN,NaN,NaN,,97
2,NaN,NaN,NaN,of fund,NaN,NaN,NaN,NaN,NaN,NaN,97
3,NaN,NaN,agency,NaN,,,,,,NaN,97
4,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,97
5,Infrastructure\nDevelopment,Construction\nof market\nshelters,LA,LGEF/L\nR,"287,500","330,625","380,219","437,252","502,839","1,938,435",97
6,NaN,Construction\nof shopping\ncenters,LA/PART\nNERS,PPP,-,-,-,"300,000",-,"300,000",97
7,NaN,Construction\nof\nRecreation\ncentres,LA/PART\nNERS,PPP,,NaN,"11,500","13,225","15,209","39,934",97
8,NaN,Construction\nof filling\nstations,LA/PART\nNERS,PPP,,"330,625",,"437,252",-,"767,877",97
9,NaN,Construction\nof Banking\nfacilities,LA/PART\nNERS,PPP,,,,"2,843,375",-,"2,843,375",97

TABLE: 47

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Construction\nof truck park\nin Bay,LA,LGEF/L\nR/PART\nNERS,"150,000",-,"1,356,000","1,532,280",-,"3,038,280.00",98
1,NaN,Construction\nof an\nEngineering\nDepot,LA,LGEF/L\nR,-,-,"500,000","565,000","638,450","1,703,450.00",98
2,NaN,Setting up of\nBlock\nmaking plant,LA,LGEF/L\nR,-,,"1,219,000","3,072,906",,"4,291,905.82",98
3,NaN,Setting up of\na metal\nfabrication\nworkshop,LA,LGEF/L\nR,-,-,"100,000","113,000","127,690","340,690.00",98
4,NaN,Rehabilitatio\nn &\nConstruction\nof Lodges,LA,LGEF/L\nR,"440,000","497,200","561,836","634,875","717,408","2,851,319.07",98
5,NaN,Construction\nof an events\nhall,LA,LGEF/L\nR,-,-,-,"1,000,000","1,130,000","2,130,000.00",98
6,NaN,Construction\nof 6 Housing\nUnits,LA,LGEF/L\nR,-,-,"2,534,792","2,534,792","2,534,792","7,604,375.01",98
7,PROGRAMME TOTAL,NaN,,,"590,000","497,200","6,554,128","9,772,077","5,148,340","22,561,744.90",98

TABLE: 48

,0,1,2,3,4,5,6,7,8,source_page
0,Objective,To Improved access to Education for all learners by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99
1,Strategy,"Enhance access to quality, equitable and inclusive education",NaN,NaN,NaN,NaN,NaN,NaN,NaN,99
2,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible Agency,99
3,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,,99
4,NaN,NaN,priority),,,,,,NaN,99
5,Infrastructure,Construction of\nClassroom blocks (1\nx3),District,5,5,5,5,5,LA/ MoGEL\nPartners,99
6,Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99
8,NaN,Rehabilitation of\nSchool infrastructure,District,1,1,1,1,1,LA/ MoGEL\nPartners,99
9,NaN,Construction of School\nVIPs,District,10,10,10,10,10,LA/ MoGEL\nPartners,99

TABLE: 49

,0,1,2,3,4,5,6,7,8,9,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
2,NaN,NaN,Purchase of school\ndesks,District,"2,000","3,000",375,375,375,LA/ MoGEL\nPartners,100
3,Upgrading,of,Write MoGE to\nupgrade community\nschools,District,,,,,,LA/ MoGEL\nPartners,100
4,Community,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
5,Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
6,Examination,NaN,Engage MoGE to\ndesignate schools in\nthe District with\nExamination centers,District,2,2,2,2,2,LA/ MoGEL\nPartners,100
7,Centers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
9,Objective,NaN,To improve health and well being of residents of Rufunsa District by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100

TABLE: 50

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101
2,NaN,Formation of District\nNutrition Coordinating\nCommittees,District,1,1,1,1,1,LA/DHO/LPHO/MA\n& Partners,101
3,NaN,Training of CBVs in\nIYCF,District,34,36,38,40,42,LA/DHO/LPHO/MA\n& Partners,101
4,Promotion of,Distribution of IEC\nmaterials,District,6000,7000,8000,9000,10000,LA/DHO/LPHO/MA\n& Partners,101
5,health education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101
6,across all,Community\nsensitizations,District,1400,1500,1600,1700,1800,LA/DHO/LPHO/MA\n& Partners,101
7,communities in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101
8,the district,Conduct quarterly\nFocus Group meetings,District,200,300,400,500,600,LA/DHO/LPHO/MA\n& Partners,101
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101

TABLE: 51

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102
2,,,,,,,,,,102
3,Strategy,Increase access to quality health care by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102
4,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible Agency,102
5,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,,102
6,NaN,NaN,priority),,,,,,NaN,102
7,Infrastructure,Construction of Health\nPosts,District,2,2,2,2,2,LA/DHO/LPHO/MA\n& Partners,102
8,Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102
9,,Upgrading of Health\nFacilities,District,5,2,2,2,2,NaN,102

TABLE: 52

,0,1,2,3,4,5,6,7,8,source_page
0,Water,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103
1,infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103
2,development and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103
3,maintenance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103
4,,Drilling of Boreholes,District,15,15,15,15,15,DWRD /LA/\nPARTNERS,103
5,NaN,Develop a water pipe\nnetwork system,Rufunsa\nTownship,0,1,1,1,1,DWRD /LA/\nPARTNERS,103
6,NaN,"Construction of piped\nwater schemes at\npublic institutions (\nschools, health centers,\nmarkets and bus\nstations)",District,1,2,10,10,5,DWRD /LA/\nPARTNERS,103
7,NaN,Rehabilitation of\nboreholes,District,12,12,12,12,12,DWRD /LA/\nPARTNERS,103
8,NaN,Construction of water\nkiosks and network\nextension,District,1,1,1,1,1,DWRD /LA/\nPARTNERS,103
9,Maintenance of,Procurement of tool\nkits for Indian Mark II,District,12,12,12,12,12,DWRD /LA/\nPARTNERS,103

TABLE: 53

,0,1,2,3,4,5,6,7,8,source_page
0,Training &,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104
1,Capacity Building,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104
3,Strategy,Increase access to improved sanitation services by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104
4,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104
5,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible Agency,104
6,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,,104
7,NaN,NaN,priority),,,,,,NaN,104
8,Sanitation,Construction of\nwaterborne sanitation\nfacilities,"Markets,\nHealth\nCenters\nSchools",2,2,2,2,2,LA / DHO/ Partners,104
9,infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104

TABLE: 54

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105
2,NaN,enumeration,District,1500,2000,2500,3000,3500,Social Welfare,105
3,NaN,Second community\nvalidation,District,1500,2000,2500,3000,3500,Social Welfare,105
4,NaN,payments of cash\ntransfers to\nbeneficiaries,District,5391,7391,9891,12891,16391,Social Welfare,105
5,NaN,Other Administrative\nCoasts,,,,,,,,105
6,NaN,Collection Of GRM\nComplaint Forms\n(CWAC areas),District,69,69,72,80,80,Social Welfare,105
7,Public Welfare,identification and\nselection of vulnerable\nindividuals using\nPWAS identification\nprocess (Wards),District,12,12,12,12,12,Social Welfare,105
8,Assistance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105
9,Scheme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105

TABLE: 55

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106
2,NaN,Savings group\nformation and\nSensitizations,District,12,12,12,12,12,Community\nDevelopment,106
3,NaN,"Trainers of Trainers\ntraining workshop in\nRevised life, sexual\nReproductive Health\nand Business Skills",District,9,0,0,0,0,Community\nDevelopment,106
4,NaN,"Community based\nvolunteers training in\nrevised life, sexual\nReproductive Health\nand Business Skills.",District,13,13,13,13,13,Community\nDevelopment,106
5,NaN,"Beneficiary training in\nrevised life, sexual\nReproductive Health\nand Business Skills.",District,281,0,0,0,0,Community\nDevelopment,106
6,NaN,Conduct training\nfeedback monitoring,District,13,13,13,13,13,Community\nDevelopment,106
7,NaN,Conduct mentorship to\nSWL beneficiaries,District,12,12,12,12,12,Community\nDevelopment,106
8,NaN,Payment of Grants for\nSWL beneficiaries,District,281,281,0,0,0,Community\nDevelopment,106
9,NaN,Training of women in\nentrepreneurship skills\nand provision of grants\nfor women Clubs,District,20,25,30,35,40,Community\nDevelopment,106

TABLE: 56

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107
2,Non formal,Refresher course for\nadult literacy\ninstructors,District,20,20,20,25,25,Community\nDevelopment,107
3,education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107
5,NaN,Revamping and\nformation of literacy\nclasses,District,20,20,20,25,25,Community\nDevelopment,107
6,NaN,Procure Teaching\nmaterial,District,4,4,4,4,4,Community\nDevelopment,107
7,Food Security,Provision of food\nsecurity Pack,District,1300,1500,1700,1900,2000,Community\nDevelopment,107
8,Pack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107
9,,Sensitization and\norientations of\nstakeholders and\ncommunities on FSP\nguidelines,District,11,11,11,11,11,Community\nDevelopment,107

TABLE: 57

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
2,NaN,Conduct Harvest\nprojection,District,1300,1500,1700,1900,2000,Community\nDevelopment,108
3,NaN,Collection of\nRecoveries,District,1300,1500,1700,1900,2000,Community\nDevelopment,108
4,Constituency,Empowerment Grants,District,200,200,200,200,200,LA,108
5,Development,Empowerment Loans,District,30,30,30,30,30,LA,108
6,Fund,Secondary School\nBoarding bursaries and\nSkills Development,District,800,800,800,800,800,LA,108
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
8,Strategy,Increase access to electricity in rural areas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
9,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible Agency,108

TABLE: 58

,0,1,2,3,4,5,6,7,8,9,source_page
0,Objective,To Improved access to Education for all learners by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
1,Strategy,"Enhance access to quality, equitable and inclusive eductaion",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
2,,,Implementing,Source of,cost per year,NaN,NaN,NaN,NaN,Total,108
3,Programme,Activities,Agency,Funds,Year 1,Year 2,Year 3,Year 4,Year 5,,108
4,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108
5,Infrastructure\nDevelopment,Construction of\nClassroom\nblocks (1 x3),"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners","6,325,000","7,273,750","8,364,813","9,619,534","11,062,465","42,645,561",108
6,NaN,Rehabilitation\nof School\ninfrastructure,"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners","454,250.00","522,387.50","600,745.63","690,857.47","794,486.09","3,062,727",108

TABLE: 59

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Construction of\nstaff houses,"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners","2,645,000","3,041,750","3,498,013","4,022,714","4,626,122","17,833,598",109
1,NaN,Construction of\nschool libraries,"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners",,,,,"2,011,357.19","2,011,357",109
2,NaN,Construction of\nScience\nLaboratories,"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners","2,100,000","1,058,000","1,216,700","1,399,205","1,609,086","7,382,991",109
3,NaN,Construction of\nComputer\nLaboratories,"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners","920,000","1,058,000","1,216,700","1,399,205","1,609,086","6,202,991",109
4,NaN,Purchase of\nSchool Desks,,,"3,000,000","4,500,000","562,500","562,500","562,500","9,187,500",109
5,Programme Total,NaN,,,"15,973,250","18,062,238","16,159,073","18,498,559","23,200,325","91,893,445",109
6,Objective,To improve health and well being of residents of Rufunsa District by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109
7,Strategy,Public Health Strengthening,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109
8,,,Implementing,Source of,cost per year,NaN,NaN,NaN,NaN,Total,109
9,Programme,Activities,Agency,Funds,Year 1,Year 2,Year 3,Year 4,Year 5,,109

TABLE: 60

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Mentorship of\nHealth Care\nProviders in\nIYCF,District,GRZ/Donor,"46,000","50,086","53,095","57,506","60,703","267,390",110
1,NaN,Expanded\nProgram for\nImmunisation,Health Facility,GRZ/Donor,"57,500","62,608","66,369","71,883","75,878","334,238",110
2,NaN,Train 30 Health\nCare Providers\nin RED/C\nstrategy,District,GRZ/Donor,"138,000","150,259","159,285","172,519","182,108","802,171",110
3,NaN,Formation of\nDistrict\nNutrition\nCoordinating\nCommittees,District,GRZ/Donor,"9,200","10,017","10,619","11,501","12,141","53,478",110
4,NaN,Training of\nCBVs in IYCF,District,GRZ/Donor,"172,500","187,824","199,106","215,649","227,635","1,002,714",110
5,Promotion of\nhealth\neducation\nacross all\ncommunities in\nthe district,Distribution of\nIEC materials,District/Facility,GRZ/Donor,"11,500","12,522","13,274","14,377","15,176","66,848",110
6,NaN,Community\nsensitizations,District/Facility,GRZ/Donor,"5,750","6,261","6,637","7,188","7,588","33,424",110
7,NaN,Conduct\nquarterly Focus\nGroup meetings,District/Facility,GRZ/Donor,"23,000","25,043","26,547","28,753","30,351","133,695",110
8,NaN,Quarterly\nmeetings with\ncommunity gate\nkeepers,District/Facility,GRZ/Donor,"40,250","43,826","46,458","50,318","53,115","233,967",110
9,NaN,Fire prevention\nsensitization,District/Facility,GRZ/Donor,"7,475","8,139","8,628","9,345","9,864","43,451",110

TABLE: 61

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Distribution of\nteaching aids\nand IEC\nmaterials,District,GRZ/Donor,"11,500","12,522","13,274","14,377","15,176","66,848",111
1,NaN,Revitalisation\nof existing non-\nfunctional\nNeighborhood\nHealth\nCommittees-\nNHCs,District,GRZ/Donor,"5,750","6,261","6,637","7,188","7,588","33,424",111
2,NaN,Support\nquarterly NHCs\nmeetings,District,GRZ/Donor,"9,200","10,017","10,619","11,501","12,141","53,478",111
3,NaN,Procure\nbicycles for\nNHCs,District,GRZ/Donor,-,-,-,-,-,-,111
4,NaN,Monitoring of\nNHCs functions,Facility,GRZ/Donor,"40,250","43,826","46,458","50,318","53,115","233,967",111
5,Programme Total,NaN,,,"1,497,875","1,630,940","1,728,904","1,872,553","1,976,630","8,706,902.13",111
6,Strategy,Increase access to quality health care,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111
7,,,Implementing,Source of,cost per year,NaN,NaN,NaN,NaN,Total,111
8,Programme,Activities,Agency,Funds,Year 1,Year 2,Year 3,Year 4,Year 5,,111
9,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111

TABLE: 62

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Construction of\nthe District\nHospital,MOH,"GRZ,\nCooperating\nPartners",,,"19,910,599",-,-,"19,910,599",112
1,NaN,Construction of\nstaff houses,"LA, Cooperating\nPartners","GRZ,\nCooperating\nPartners","3,450,000","1,252,161","2,000,000","1,437,661","3,035,133","11,174,955",112
2,NaN,Incinerator\nConstruction,"MOH, LA,\nCooperating\nPartners","GRZ,\nCooperating\nPartners","115,000","125,216","132,737","143,766","151,757","668,476",112
3,NaN,Purchase of\nAmbulance,,,Mpanshya,,"1,000,000",,,,112
4,First Aid\nPromotion,Training of\nHealth care\nworkers/\ndrivers/CBVs in\nFirst Aid\nPromotion,District,GRZ/Donor,"172,500","187,824","199,106","215,649","227,635","1,002,714",112
5,,NaN,,,,,,,,,112
6,Programme Total,NaN,,,"8,107,500","4,695,604","26,560,876","5,391,229","7,208,441","50,963,649",112
7,Objective,To provide improved access to clean water and sanitation by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112
8,Strategy,Improve access to clean and safe water sources,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112
9,,,Implementing,Source of,cost per year,NaN,NaN,NaN,NaN,Total,112

TABLE: 63

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Drilling of\nBoreholes,LA / DWRD,GRZ\nPARTNERS,"1,169,984.70","1,273,921.05","1,350,440.39","1,462,644.62","1,543,938.73","6,800,929.50",113
1,NaN,Develop a water\npipe network\nsystem in\nRufunsa\nTownship,LA / DWRD,GRZ\nPARTNERS,-,"294,257.84","311,932.73","337,850.32","356,628.12","1,300,669.00",113
2,NaN,"Construction of\npiped water\nschemes at\npublic\ninstitutions (\nschools, health\ncenters, markets\nand bus\nstations)",LA / DWRD,GRZ\nPARTNERS,"250,000.00","700,000.00","1,000,000.00","1,500,000.00","2,000,000.00","5,450,000.00",113
3,NaN,Rehabilitation\nof Boreholes,LA / DWRD,GRZ\nPARTNERS,"300,000.00","329,700.00","362,340.30","398,211.99","437,634.98","1,827,887.27",113
4,NaN,Construction of\nwater kiosks\nand netwrok\nextension,LA / DWRD,,"300,000",329700,362340.3,398211.9897,437634.9767,"1,827,887.27",113
5,Maintenance of\nwater points,Procurement of\ntool kits for\nIndian Mark II,LA / PARTNERS,GRZ\nPARTNERS,"83,605.00","91,032.10","96,500.04","104,517.95","110,327.08","485,982.18",113
6,Water resources\nassessment and\nquantification,Conduct field\nappraisals for\nrehabilitation of\nbroken down\nboreholes,LA / PARTNERS,GRZ\nPARTNERS,"17,077.50","18,594.59","19,711.49","21,349.27","22,535.86","99,268.71",113

TABLE: 64

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Conduct water\nquality\nmonitoring for\nexisting water\npoints in the\nDistrict,LA / DWRD /\nDHO,GRZ\nPARTNERS,"40,089.00","43,650.33","46,272.23","50,116.86","52,902.37","233,030.79",114
1,Training &\nCapacity\nBuilding,Train and re-\norient V-Washe\ncommittee\nmembers,LA / DWRD/\nPARTNERS,GRZ\nPARTNERS,"56,580.00","61,606.32","65,306.77","70,732.92","74,664.27","328,890.28",114
2,StrategyTotal,NaN,,,"2,257,011.20","3,240,631.66","7,576,389.86","4,393,235.22","5,088,622.43","22,555,890.37",114
3,Strategy,Increase access to improved sanitation services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114
4,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114
5,Sanitation\ninfrastructure\ndevelopment,Construction of\nwaterborne\nsanitation\nfacilities,,,"250,000","274,750.00","301,950.25","331,843.32","364,695.81","1,523,239.39",114
6,NaN,Upgrading of\npit latrines to\nwater borne\nsanitation at\npublic\ninstitutions,,,,,"250,000.00","274,750.00","301,950.25","826,700.25",114
7,Sanitation and\nPersonal\nHygiene\nPromotion,CLTS\nCommunity\nmeetings,LA / DWRD/\nPARTNERS,GRZ\nPARTNERS,"79,350.00","86,399.11","91,588.76","99,198.61","104,712.09","461,248.56",114
8,NaN,backstopping\nvisits to\nsensitized\ntriggered\nvillages,LA / DWRD/\nPARTNERS,GRZ\nPARTNERS,"46,000.00","50,086.44","53,094.93","57,506.44","60,702.66","267,390.47",114

TABLE: 65

,0,1,2,3,4,5,6,7,8,9,source_page
0,Objective,To Reduce Poverty and Inequalities Levels by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115
1,Strategy,Enhance welfare and livelyhoods of poor and vulnerable people.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115
2,Programme,Activities,Implementing,Source of,cost per year,NaN,NaN,NaN,NaN,Total,115
3,NaN,NaN,Agency,Funds,Year 1,Year 2,Year 3,Year 4,Year 5,,115
4,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115
5,Social Cash\nTransfer,Awareness\nraising (Wards),Social Welfare,GRZ,"46,000.00","50,086.44","53,094.93","57,506.44","60,702.66","267,390.47",115
6,NaN,Disability\nCertification,Social Welfare,GRZ,"46,000.00","50,086.44","53,094.93","57,506.44","60,702.66","267,390.47",115
7,NaN,listing of\npotential\nbeneficiries,Social Welfare,GRZ,"69,000.00","75,129.66","79,642.40","86,259.66","91,053.99","401,085.70",115
8,NaN,first community\nvalidation,Social Welfare,GRZ,"46,000.00","50,086.44","53,094.93","57,506.44","60,702.66","267,390.47",115
9,NaN,enumeration,Social Welfare,GRZ,"184,000.00","200,345.76","212,379.73","230,025.75","242,810.63","1,069,561.87",115

TABLE: 66

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Health care\nsupport,Social Welfare,GRZ,"34,500.00","37,564.83","39,821.20","43,129.83","45,526.99","200,542.85",116
1,NaN,Repatriation of\nstranded\nperesons,Social Welfare,GRZ,"34,500.00","37,564.83","39,821.20","43,129.83","45,526.99","200,542.85",116
2,NaN,Primary and\nsecondary\neducation\nsupport,Social Welfare,GRZ,"115,000.00","125,216.10","132,737.33","143,766.10","151,756.65","668,476.17",116
3,NaN,community\nvulnarable\nsupport,Social Welfare,GRZ,"172,500.00","187,824.15","199,105.99","215,649.14","227,634.97","1,002,714.26",116
4,Programme Total,NaN,,,,,,,,,116
5,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,116
6,,NaN,NaN,NaN,"402,500.00","438,256.35","464,580.65","503,181.33","531,148.26","2,339,666.60",116
7,Women and\nyouth\nempowerment,Training of\nGrievance\nredress\nmechanism\nFocal Persons,Community\nDevelopment,GRZ,"17,250.00","18,782.42","19,910.60","21,564.91","22,763.50","100,271.43",116
8,NaN,Grievance\nredress\nmechanism\nsensitization,Community\nDevelopment,GRZ,"23,000.00","25,043.22","26,547.47","28,753.22","30,351.33","133,695.23",116

TABLE: 67

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Training of\nwomen in\nentrepreneurshi\np skills and\nprovision of\ngrants for\nwomen Clubs,Community\nDevelopment,GRZ,"17,250.00","18,782.42","19,910.60","21,564.91","22,763.50","100,271.43",117
1,Programme Total,NaN,,,,,,,,,117
2,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,117
3,,NaN,NaN,NaN,"86,250.00","93,912.08","99,553.00","107,824.57","113,817.48","501,357.13",117
4,Community\nSelf-help\nprograms,Community\nsensitization on\ncommunity\nself-projects,Community\nDevelopment,GRZ,"11,500.00","12,521.61","13,273.73","14,376.61","15,175.66","66,847.62",117
5,Non formal\neducation,Refresher\ncourse for adult\nliteracy\ninstructors,Community\nDevelopment,GRZ,"11,500.00","12,521.61","13,273.73","14,376.61","15,175.66","66,847.62",117
6,NaN,Revamping and\nformation of\nliteracy classes,Community\nDevelopment,GRZ,"11,500.00","12,521.61","13,273.73","14,376.61","15,175.66","66,847.62",117
7,NaN,Procure\nTeaching\nmaterial,Community\nDevelopment,GRZ,"11,500.00","12,521.61","13,273.73","14,376.61","15,175.66","66,847.62",117
8,Programme Total,NaN,,,,,,,,,117
9,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,117

TABLE: 68

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,community\nselection and\nallocation of\ncaseloads,Community\nDevelopment,GRZ,-,-,-,-,-,-,118
1,NaN,"targeting\nbeneficiary\nhouseholds for\nsupport,\nListing,\nCommunity\nvalidation, Self-\nregistration and\nLottery",Community\nDevelopment,GRZ,"23,000.00","25,043.22","26,547.47","28,753.22","30,351.33","133,695.23",118
2,NaN,Training of\nVulnerable but\nViable farmers\ninto farming\nmethods,Community\nDevelopment,GRZ,"11,500.00","12,521.61","13,273.73","14,376.61","15,175.66","66,847.62",118
3,NaN,Distribution of\nInputs,Community\nDevelopment,GRZ,"23,000.00","25,043.22","26,547.47","28,753.22","30,351.33","133,695.23",118
4,NaN,Monitoring of\ncrop\nperformance,Community\nDevelopment,GRZ,"18,594.59","19,711.49","21,349.27","22,535.86","12,140.53","94,331.74",118
5,NaN,Conduct\nHarvest\nprojection,Community\nDevelopment,GRZ,"9,200.00","10,017.29","10,618.99","11,501.29","12,140.53","53,478.09",118
6,NaN,Collection of\nRecoveries,Community\nDevelopment,GRZ,"9,200.00","10,017.29","10,618.99","11,501.29","12,140.53","53,478.09",118
7,Programme Total,NaN,,,,,,,,,118
8,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,118
9,,NaN,NaN,NaN,"124,394.59","134,910.31","143,467.61","154,800.67","151,756.65","709,329.82",118

TABLE: 69

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Empoweremnet\nLoans,Local Authority,CDF,"3,369,270.00","3,668,581.30","3,888,938.29","4,212,059.05","4,446,166.22","19,585,014.87",119
1,NaN,Secondary\nSchool\nBoarding\nbusaries and\nSkills\nDevelopment,Local Authority,CDF,"5,615,450.00","6,114,302.16","6,481,563.82","7,020,098.42","7,410,277.04","32,641,691.44",119
2,Programme,,,,,,,,,,119
3,NaN,,,,NaN,NaN,,,,,119
4,Total,NaN,NaN,NaN,"11,230,900.0","12,228,604.3",NaN,NaN,NaN,NaN,119
5,,"65,283,382.89",NaN,NaN,0,3,"12,963,127.64","14,040,196.84","14,820,554.08","65,283,382.89",119
6,Strategy,Increase access to electricity in rural areas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119
8,Rural\nElectrification,Electrification\nof unserved\ncommunities\nand public\ninstitutions,LA/REA,CDF,,"1,000,000.00","1,099,000.00","1,207,801.00","1,327,373.30","4,634,174.30",119
9,GOAL\nTOTAL,,,,"41,525,625.3\n8","42,534,490.9\n9","67,826,517.10","47,268,558.80","78,149,656.01","280,939,022.59",119

TABLE: 70

,0,1,2,3,4,5,6,7,8,source_page
0,Objective,Increased adaptive Capacity to Climate Change by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120
1,Strategy,Strengthen Climate Change Adaptition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120
2,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible,120
3,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Agency,120
4,NaN,NaN,priority),,,,,,,120
5,Community,Conduct sensitisation and\nawareness meetings,District,12,12,12,12,12,Forestry,120
6,education and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120
7,awareness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120
8,Sustainable,Conduct general forest\npatrols,District,16,16,16,16,16,Forestry,120
9,Forest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120

TABLE: 71

,0,1,2,3,4,5,6,7,8,source_page
0,Parks and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121
1,Gardens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121
3,NaN,Tree Planting,District,400,400,400,400,400,LA/Forestry,121
4,NaN,Maintaenance of open\nspaces,District,1,3,3,3,3,LA,121
5,Environmental,Conduct enforcement of\nenvironmental regulations,District,10,10,10,10,10,LA,121
6,Regulations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121
7,,Environmental and Social\nImpact Assessments,District,12,12,12,12,12,LA,121
8,Environmental,Mapping of Heritage sites,District,1,2,0,0,1,LA,121
9,Protection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121

TABLE: 72

  0  source_page
0            122
1            122

TABLE: 73

,0,1,2,3,4,5,6,7,8,9,source_page
0,Objective,Increased adaptive Capacity to Climate Change by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122
1,Strategy,Strengthen Climate Change Adaptition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122
2,Programme,Activities,Implementing,Source of fund,Cost per year,NaN,NaN,NaN,NaN,Tot,122
3,NaN,NaN,agency,NaN,Year 1,Year 2,Year 3,Year 4,Year 5,,122
4,,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,122
5,Community\neducation and\nawareness,Conduct\nsensitisation\nmeetings,Forestry,GRZ,"5,750.00","6,260.81","6,636.87","7,188.30","7,587.83",NaN,122
6,Sustainable\nForest\nManagement,Conduct\ngeneral forest\npatrols,Forestry,GRZ,"172,500.00","187,824.15","199,105.99","215,649.14","227,634.97",NaN,122
7,NaN,Conduct\nbeekeeping\ntrainings,Forestry,GRZ,"28,750.00","31,304.03","33,184.33","35,941.52","37,939.16",NaN,122
8,NaN,Raise ad plant\nnursery\nseedlings,Forestry,GRZ,"28,750.00","31,304.03","33,184.33","35,941.52","37,939.16",NaN,122
9,Sustainable\nWildlife\nManagement,Preparation of\nGame\nManagement\nPlans,GRZ/BCP,BCP/DNPWL,"230,000.00","250,432.20","265,474.66","287,532.19","303,513.29",NaN,122

TABLE: 74

,0,1,2,3,4,5,6,7,8,9,source_page
0,,NaN,HIVOs,HIVOS,"115,000.00","125,216.10","132,737.33","143,766.10","151,756.65",NaN,123
1,Programme\nTotal,,,,"829,344.59","902,485.00","957,147.44","1,036,086.83","1,221,641.00",NaN,123
2,Objective,To improve environmental sustainability by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123
3,Programme,Activities,Implementing,Source of fund,Cost per year,NaN,NaN,NaN,NaN,Tot,123
4,NaN,NaN,agency,NaN,Year 1,Year 2,Year 3,Year 4,Year 5,,123
5,,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,123
6,Parks and\nGardens,Obtaining\ncertificate of\ntitle for open\nspaces within\nthe township,LA,LA,"11,500.00","18,940.00",-,-,-,NaN,123
7,NaN,Tree Planting,LA,LA/Cooperating\nPartners,"11,500.00","30,000.00","13,273.73","14,376.61","15,175.66",NaN,123
8,NaN,Maintenance\nof open spaces,LA,LA/Cooperating\nPartners,"1,000.00","10,017.29","10,618.99","11,501.29","12,140.53",NaN,123
9,Environmental\nRegulations,Conduct\nenforcement\nof\nenvironmental\nregulations,LA,LA,"6,000.00","7,512.97","7,964.24","8,625.97","9,105.40",NaN,123

TABLE: 75

,0,1,2,3,4,5,6,7,8,9,source_page
0,Objective,To enhance Solid Waste Management System in the District by 2034,NaN,NaN,NaN,NaN,NaN,NaN,,,124
1,Strategy,Provision of infrastructure and equipment,NaN,NaN,NaN,NaN,NaN,NaN,,,124
2,Programme,Activities,Implementing,Source of fund,Cost per year,NaN,NaN,NaN,NaN,Tot,124
3,NaN,NaN,agency,NaN,Year 1,Year 2,Year 3,Year 4,Year 5,,124
4,,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,124
5,Preparation of\na district solid\nwaste\nmanagement\nplan,Preparation of\nSolid waste\nmanagement\nplan,Local\nAuthority,,"10,580.00",-,-,-,-,NaN,124
6,Infrastructure\ndevelopment,Construction\nof refuse bays,Local\nAuthority,LA,-,"87,000.15","92,225.90","99,888.68","105,440.52",NaN,124
7,NaN,Installation of\nskip bins,Local\nAuthority,LA,-,,"185,832.26","100,636.27","106,229.65",NaN,124
8,Procurement\nof refuse\nmanagement\nequipment,Procurement\nof a refuse\ntruck,Local\nAuthority,GRZ/LA,-,"2,253,889.80",-,-,-,NaN,124
9,NaN,Procurement\nof a refuse\nskip collector,Local\nAuthority,GRZ/LA,-,,-,-,"2,807,497.96",NaN,124

TABLE: 76

,0,1,2,3,4,5,6,7,8,source_page
0,Objective,To enhance citizen participation in development by 2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125
1,Strategy,Operationalise Ward Development Committees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125
2,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible,125
3,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Agency,125
4,NaN,NaN,priority),,,,,,,125
5,Ward Development,Orientation of WDCs,District,12,12,12,12,12,LA,125
6,Committees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125
7,,Implementation of WDF\nprojects,District,12,12,12,12,12,LA,125
8,NaN,Construction of WDC Offices,Wards,,,4,4,4,LA,125
9,Objective,Create and maintain a mutual relationship between the Local Authority and its publics by 2029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125

TABLE: 77

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126
2,NaN,Media Tours,Rufunsa,1,1,1,1,1,LA,126
3,NaN,Development of Grievance\nMechanism Strategy,Rufunsa,1,,,,,LA,126
4,Objective,To improve the registration of land by 2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126
5,Strategy,Strengthening Land registration systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126
6,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible,126
7,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Agency,126
8,NaN,NaN,priority),,,,,,,126
9,Land Management,Development of LAP in\nSinjela and Shikabeta,Rufunsa\nShikabeta\nTownships,1,1,-,-,-,LA,126

TABLE: 78

,0,1,2,3,4,5,6,7,8,source_page
0,ICT for public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127
1,service delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127
2,,Installation of LAN,Township,1,1,1,1,1,LA,127
3,NaN,Procurement of ICT\nequipment and Software,Township,35,10,10,10,10,LA,127
4,NaN,Capacity building in ICT,Township,,2,1,1,1,LA,127
5,NaN,E Payment systems,Township,,1,1,1,1,LA,127
6,Objective,To Improve Postal and Radio Services by 2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127
7,Strategy,construction postal and radio service infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127
8,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible,127
9,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Agency,127

TABLE: 79

,0,1,2,3,4,5,6,7,8,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128
2,Objective,To provide District Administration infrastructure to support governance systems by 2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128
3,Strategy,Completion of on-going government infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128
4,Programme,Activities,Location,Target,Target,Target,Target,Target,Responsible,128
5,,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Agency,128
6,NaN,NaN,priority),,,,,,,128
7,Infrastructure,Construction of District\nAdmin Block,Township,0,1,0,0,0,MIHUD,128
8,Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128
9,,Construction of Council\nAdmin Block & 2 High Cost\nHouses & External Works,Township,0,1,0,0,0,MIHUD,128

TABLE: 80

,0,1,2,3,4,5,6,7,8,9,source_page
0,Objective,To enhance citizen participation in development by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129
1,Strategy,Operationalise Ward Development Committees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129
2,,,Implementi,Sourc,Cost per year,NaN,NaN,NaN,NaN,Total,129
3,Programme,Activities,NaN,e of,,NaN,NaN,NaN,NaN,,129
4,NaN,NaN,ng agency,NaN,Year 1,Year 2,Year 3,Year 4,Year 5,,129
5,,,NaN,fund,NaN,NaN,NaN,NaN,NaN,NaN,129
6,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,,129
7,NaN,NaN,NaN,,,,,,,NaN,129
8,Ward\nDevelopmen\nt Committees,Orientation\nof WDCs,LA,GRZ,"69,000","75,130","79,642","86,260","91,054","401,085.70",129
9,NaN,Implementati\non of WDF\nprojects,"LA, WDC",GRZ,"128,800","140,242","148,666","161,018","169,967","748,693.31",129

TABLE: 81

,0,1,2,3,4,5,6,7,8,9,source_page
0,Objective,To improve the registration of land by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130
1,Strategy,Strengthening Land registration systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130
2,Programme,Activities,Implementi,Sourc,Cost per year,NaN,NaN,NaN,NaN,Total,130
3,NaN,NaN,NaN,e of,Year 1,Year 2,Year 3,Year 4,Year 5,,130
4,NaN,NaN,ng agency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130
5,,,NaN,fund,NaN,NaN,NaN,NaN,NaN,,130
6,NaN,NaN,,NaN,,,,,,NaN,130
7,Land\nManagement\nand\nAdministrati\non,Development\nof LAP in\nSinjela and\nShikabeta,LA,GRZ,"23,000","187,824","663,687",0,0,"874,510.80",130
8,NaN,Maintainance\nof land\ndatabase in\nSinjela and\nRufunsa\nTownship,LA,GRZ,"23,000","25,043","26,547","28,753","30,351","133,695.23",130
9,NaN,Community\nSensitisation\non planning\nlaws and\nregulations,LA,GRZ,"23,000","25,043","26,547","28,753","30,351","133,695.23",130

TABLE: 82

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Development\nand\ndistribution\nof Municipal\nService\nCharters,LA,GRZ,,"30,000.00","32,970.00",,,"62,970.00",131
1,ICT for\npublic\nservice\ndelivery,Installation\nof LAN and\nmaintenance,LA,GRZ,"80,000.00","18,782.42","19,910.60","21,564.91","22,763.5\n0","163,021.43",131
2,NaN,Procurement\nof ICT\nequipment\nand Software,LA,GRZ,"459,940.00","313,040.25","265,474.66","215,649.14","151,756.\n65","1,405,860.7\n0",131
3,NaN,Capacity\nbuilding in\nICT,LA,GRZ,"30,000.00","18,782.42","19,910.60","21,564.91","22,763.5\n0","113,021.43",131
4,NaN,E Payment\nsystems,LA,GRZ,"120,000.00","12,521.61","13,273.73","14,376.61","15,175.6\n6","175,347.62",131
5,Programme\nTotal,,,,"689,940.00","2,393,126.6\n9","351,539.59","273,155.58","212,459.\n30","3,920,221.1\n7",131
6,Objective,To Improve Postal and Radio Services by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131
7,Strategy,construction postal and radio service infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131
8,Programme,Activities,Implementi,Sourc,Cost per year,NaN,NaN,NaN,NaN,Total,131
9,NaN,NaN,NaN,e of,Year 1,Year 2,Year 3,Year 4,Year 5,,131

TABLE: 83

,0,1,2,3,4,5,6,7,8,9,source_page
0,NaN,Completion\nof Rufunsa\nPost Office,MIHUD,GRZ,0,0,"2,654,747",0,0,"2,654,746.6\n0",132
1,Programme\nTotal,,,,0,0,2986589.9\n23,0,0,"2,986,589.9\n2",132
2,Objective,To enhance public order and safety by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132
3,Strategy,Enhance public safety and order infrastructure and services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132
4,Programme,Activities,Implementi,Sourc,Cost per year,NaN,NaN,NaN,NaN,Total,132
5,NaN,NaN,NaN,e of,Year 1,Year 2,Year 3,Year 4,Year 5,,132
6,NaN,NaN,ng agency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132
7,,,NaN,fund,NaN,NaN,NaN,NaN,NaN,,132
8,NaN,NaN,,NaN,,,,,,NaN,132
9,Infrastructur\ne\nDevelopmen\nt,Construction\nof Fire\nstation,"LA,\nMLGRD",GRZ,0,0,0,"2,659,673",0,"2,659,672.7\n6",132

TABLE: 84

,0,1,2,3,4,5,6,7,8,9,source_page
0,Programme\nTotal,,,,569250,15652.0125,2749403.0\n28,2659672.7\n59,0,"6,993,977.8\n0",133
1,Objective,To provide District Adminstration infrastructure to support governce systems by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133
2,Strategy,Completion of on-going government infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133
3,,,Implementi,Sourc,Cost per year,NaN,NaN,NaN,NaN,Total,133
4,Programme,Activities,NaN,e of,Year 1,Year 2,Year 3,Year 4,Year 5,,133
5,NaN,NaN,ng agency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133
6,,,NaN,fund,NaN,NaN,NaN,NaN,NaN,,133
7,NaN,NaN,,NaN,,,,,,NaN,133
8,Infrastructur\ne\nDevelopmen\nt,Completion\nof District\nAdmin Block,MIHUD,GRZ,0,"4,382,564",0,0,0,"4,382,563.5\n0",133
9,NaN,Completion\nof Council\nAdmin Block\n& 2 High\nCost Houses\n& External\nWorks,MIHUD,GRZ,0,"5,759,941",0,0,0,"5,759,940.6\n0",133

TABLE: 85

,0,1,2,3,4,5,6,7,source_page
0,S/,Goals,,,,,,Total,134
1,N,,Year 1,Year 2,Year 3,Year 4,Year 5,,134
2,NaN,NaN,,,,,,NaN,134
3,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134
4,1,To transform the,"95,250,016.4\n0","16,443,835.3\n4","32,667,953.0\n9","166,843,067.1\n3","173,462,106.66","484,666,978.6\n2",134
5,,Local Economy of,NaN,NaN,NaN,NaN,NaN,NaN,134
6,NaN,Rufunsa and Create,NaN,NaN,NaN,NaN,NaN,NaN,134
7,NaN,Jobs,NaN,NaN,NaN,NaN,NaN,NaN,134
8,2,To enhance human,"41,525,625.3\n8","42,534,490.9\n9","67,826,517.1\n0","47,268,558.80","78,149,656.01","277,304,848.2\n8",134
9,,and social,NaN,NaN,NaN,NaN,NaN,NaN,134

TABLE: 86

,0,1,2,source_page
0,Key Considerations for\nSpatial Analysis,Key Considerations For A\nSpatial Development\nStrategy,"Issues To Be Considered In\nAligning Spatial Strategy With\nIDP Objectives, Strategies and\nProjects",141
1,To provide effective sustainable municipal service delivery,NaN,NaN,141
2,Identify areas which are\nnot receiving municipal\nservices,Mapping out areas and service\nthat are being offered.,Considering the quality of services.,141
3,Improved telecommunication and postal services,NaN,NaN,141
4,Mapping current\ncommunication towers and\ntheir mobile coverage,Identifying areas without\nmobile coverage,Areas that are highly populated but\nwithout mobile coverage,141
5,To improve delivery of quality educational services,NaN,NaN,141
6,Mapping out current\nschools in the district,Identify areas in need of\nschools,"Considering factors that can\nimprove the quality of service i.e.\npopulation, distance to nearest\nschool, Infrastructure, staffing",141
7,To improve the health status of people in Zambia in order to contribute to increased\nproductivity and socio-economic development,NaN,NaN,141

TABLE: 87

,0,1,2,source_page
0,,.,,142
1,To improve availability and accessibility to clean and safe water supply and sanitation for\nall.,NaN,NaN,142
2,Identify areas that do not\nhave access to clean and\nsafe water.,Monitoring people accessing\nwater points,Maintenance of existing water\nsupply points one installed.,142
3,To alleviate poverty and reduce unemployment in the district.,NaN,NaN,142
4,Mapping poverty stricken\nareas.\nIdentifying areas that\nrequire urgent attention.,Monitoring of poverty trends\nin the various areas within the\ndistrict.,Identify alternative livelihoods,142
5,Local economic development,NaN,NaN,142
6,Mapping out areas with\npotential type of resources\navailable.,Quantity and quality of\nresources,Assessment of Potential Impacts.,142
7,A financially viable and sustainable municipality.,NaN,NaN,142
8,Identifying Potential\nRevenue Site Sources.,Mapping Out Potential\nRevenue Sites.,Assessment of Revenue to be\nRealised.,142
9,A sustainable health and living environment,NaN,NaN,142

TABLE: 88

,0,1,2,3,4,5,6,7,8,9,source_page
0,REVENUE,2019,,,2020,,,2021,,,145
1,ITEM,BUDGETE\nD,ACTUA\nL,%,BUDGET\nED,ACTUA\nL,%,BUDGE\nTED,ACTU\nAL,%,145
2,LOCAL\nTAXES,"23,010","20,435",89,"22,500","22,633",10\n1,"26,634","23,766",89,145
3,FEES &\nCHARGE\nS,"808,303","287,345",36,"853,460","888,031",10\n4,"5,673,254","2,023,1\n45",36,145
4,LICENCE\nS,"115,569","42,094",36,"135,242","77,202",57,"310,622","59,339",19,145
5,LEVIES,"378,783","490,090",12\n9,"319,221","322,519",10\n1,"508,600","268,985",53,145
6,PERMITS,"43,896","16,548",38,"36,754","29,946",81,"69,361","91,858",132,145
7,NATIONA\nL\nSUPPORT,"6,797,893","6,733.34",99,"8,083,393","7,186,78\n6",89,"7,900,000","6,120,5\n21",78,145
8,CDF,"1,400,000",0,0,"1,600,000.\n00","1,600,00\n0.00",10\n0,"1,600,000\n.00","1,600,0\n00.00",100,145
9,,,,,,,,,,,145

TABLE: 89

,0,1,2,3,4,5,6,source_page
0,REVENUE PROJECTION FOR THE NEXT 5 YEARS,NaN,NaN,NaN,NaN,NaN,NaN,149
1,,NaN,NaN,NaN,NaN,NaN,NaN,149
2,YEARS,2022,2023,2024,2025,2026,TOTAL,149
3,,,,,,,NaN,149
4,Locally Generated Revenue,"7,522,661","5,792,574","6,371,831","7,009,015","7,709,916","34,405,997",149
5,Constituency Development\nFund,"25,700,000","28,300,000","28,300,000","28,300,000","28,300,000","138,900,00\n0",149
6,Capital (20% of LGEF),"2,055,625.8\n2","2,055,625.8\n2","2,055,625.8\n2","2,055,625.8\n2","2,055,625.8\n2","10,278,129",149
7,TOTAL,"35,278,287","36,148,200","36,727,457","37,364,641","38,065,542","183,584,12",149
8,NaN,NaN,NaN,NaN,NaN,NaN,6,149
9,,,,,,,NaN,149

TABLE: 90

,0,1,2,3,4,5,6,source_page
0,,2022,2023,2024,2025,2026,Total,149
1,,NaN,NaN,NaN,NaN,NaN,NaN,149
2,NaN,,,,,,,149
3,Local Taxes,"15,000.00","34,185","37,604","41,364","45,500","173,653",149
4,NaN,NaN,NaN,NaN,NaN,NaN,,149
5,Fees and Charges,"1,943,099.00","1,248,304.00","1,373,134","1,510,448","1,661,493","7,736,478",149
6,NaN,NaN,NaN,NaN,NaN,NaN,,149
7,Licences,"68,534.00","73,100.00","80,410","88,451","97,296","407,791",149
8,NaN,NaN,NaN,NaN,NaN,NaN,,149
9,Levies,"178,293.00","184,525.00","202,978","223,275","245,603","1,034,674",149

TABLE: 91

,0,1,2,3,4,5,6,source_page
0,YEARS,202,202,2024,2025,2026,TOTA,150
1,NaN,2,3,NaN,NaN,NaN,L,150
2,,NaN,NaN,,,,NaN,150
3,CDF,"25,700,0\n00","28,300,0\n00","28,300,\n000","28,300,0\n00","28,300,000","138,900,00\n0.00",150
4,TOTAL,"25,700,0","28,300,0","28,300,","28,300,0","28,300,000","138,900,00",150
5,NaN,00,00,000,00,,0.00,150
6,,NaN,NaN,NaN,NaN,NaN,NaN,150
7,NaN,,,,,NaN,,150

TABLE: 92

,0,1,2,3,4,5,6,source_page
0,YEARS,2022,2023,2024,2025,2026,TOTAL,150
1,Capital\nComponent\n(Annual),"2,055,625.\n82","2,055,625.\n82","2,055,625\n.82","2,055,625\n.82","2,055,625.\n82","10,278,12\n9.00",150
2,,"2,055,625.","2,055,625.","2,055,625","2,055,625","2,055,625.","10,278,12",150
3,NaN,NaN,82,.82,.82,82,9.00,150
4,NaN,82,NaN,NaN,NaN,NaN,NaN,150
5,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,150
6,NaN,,,,,,,150

TABLE: 93

,0,1,2,3,4,5,6,7,source_page
0,,Implementing,Estimated Income per year,NaN,NaN,NaN,NaN,,150
1,Programme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150
2,NaN,Agency,2023,2024,2025,2026,2027,Total,150
3,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150
4,NaN,,NaN,NaN,NaN,NaN,NaN,,150
5,Construction of truck\npark in Bay,LA,-,"396,000","435,600","479,160","527,076",,150
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,837,836",150
7,Construction of an\nEngineering Depot,LA,-,"132,000","145,200","159,720","175,692",,150
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"612,612",150

TABLE: 94

,0,1,2,3,4,5,6,7,source_page
0,Setting up Block\nmaking Plant,LA,-,"264,000","290,000","319,000","351,384",,151
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,224,384",151
2,Setting up of a metal\nfabrication workshop,LA,-,,"145,200","159,720","175,692",,151
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"480,612",151
4,Construction of an\nevents hall,LA,-,-,,,"351,384",,151
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"351,384",151
6,Rehabilitation &\nConstruction of Lodges,LA,-,"110,000","121,000","133,000","146,410",,151
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"369,600",151
8,Construction of 9\nHousing Units,LA,-,"52,800","79,200","105,600","132,000",,151
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"393,600",151

TABLE: 95

,0,1,2,3,4,5,6,source_page
0,REVENUE PROJECTION FOR THE NEXT 5 YEARS,NaN,NaN,NaN,NaN,NaN,NaN,151
1,,NaN,NaN,NaN,NaN,NaN,NaN,151
2,YEARS,2022,2023,2024,2025,2026,TOTAL,151
3,,,,,,,NaN,151
4,Locally Generated Revenue,"7,522,661","5,792,574","6,371,831","7,009,015","7,709,916","34,405,997",151
5,Constituency Development Fund,"25,700,000","28,300,000","28,300,000","28,300,000","28,300,000","138,900,000",151
6,Capital (20% of LGEF),"2,055,625.82","2,055,625.82","2,055,625.82","2,055,625.82","2,055,625.82","10,278,129",151
7,RIDP Projects (Revenue),0,"99,526.00","1,064,280.00","1,336,628.00","1,488,470.00","3,988,904",151
8,TOTAL,"35,278,287","36,247,726","37,791,737","38,701,269","39,554,012","187,573,030",151
9,,,,,,,,151

TABLE: 96

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,Farmer Support Programme by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154
1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154
2,Strategy,promote diversification within the agriculture sector,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154
3,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154
4,Programme,Infrastructure Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154
5,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154
6,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Frequen,Responsibl,154
7,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Informati,cy,e Agency/,154
8,NaN,priority),,,,,,,on,,Officer,154
9,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,154

TABLE: 97

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
2,Setting up and,"Nyamphand\ne,\nkanyongolo\nka, Munyeta\nand\nLukwipa",,1,1,1,1,Number of\nAqua cultural\nparks\nconstructed,Project\nReports,Quarterl\ny,MFL,155
3,development of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
4,aqua cultural,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
5,parks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
6,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
7,Construction of,"Rufunsa,\nMpanshya,\nSinjela,\nKabuyu,\nMunyeta,\nNamanongo\n,\nKanyongolo\nka",,2,2,2,2,Number of\nDip tanks\nConstructed,Project\nReports,Quarterl\ny,MFL,155
8,Dip Tanks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155

TABLE: 98

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Rehabilition of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
1,Staff Houses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
3,Programme,Livestock Re-Stocking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
4,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
5,Livestock Pass-,Rufunsa\nDistrict,240,240,240,240,240,Number of\nLivestock\npassed on,Departme\nntal report,Quarterl\ny,Scrala and\nWorld\nVision,156
6,on Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
8,Programme,Extension services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156
9,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156

TABLE: 99

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Promotion of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
1,farm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
2,Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
3,Skills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
5,Nutritional,Agricultural\nCamps,510,510,510,510,510,Number of\nframers\nreached,Activity\nreport,Annually,DACO\nPartners,157
6,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157
8,Extension,Agricultural\nCamps,19,20,21,22,23,Number of\nframers\ntrained,Activity\nreport,Annually,DACO,157
9,Methodology -,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157

TABLE: 100

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Provincial and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
1,District shows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
3,Agriculture,Agricultural\nCamps,5,4,5,4,4,Number of\nnews articles\npublished,Activity\nReport,Quarterl\ny,DACO,158
4,Information,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
5,collection and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
6,Dissemination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
7,of news,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
9,Programme,Promotion of Agricultural Mechanization and ADP technologies.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158

TABLE: 101

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Training of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
1,farmers in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
2,protection of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
3,water catchment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
4,areas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
6,Farmer trainings,District,750,750,1500,3000,4500,Number of\nfarmers\ntrained,Activity\nReport,Quarterl\ny,Livestock\nDepartment,159
7,in livestock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
8,production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159

TABLE: 102

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Programme,Organic Farming Promotion and Natural Soil Enhancement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
2,"Trainings,","Mwachilelel\ne,\nNyangwena\nand Sinjela",1,1,1,1,1,Number of\nfares\nundertaken,Activity\nReport,Quarterl\ny,Kasis\nAgriculture\nTraining\nCentre\n(KATC),160
3,Demonstration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
4,and Food Fares,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
6,Programme,Agriculture Insurance Access Promotion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
7,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160
8,Trainings and,Rufunsa,"12,142","12,142","12,142","12,142","12,142",Number of\nfarmers\nattended\ntrainings,Activity\nReport,Quarterl\ny,DACO,160
9,Sensitizations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160

TABLE: 103

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
2,Cooperative,Rufunsa,205,205,205,205,205,Number of\ninspections\nundertaken,Departme\nntal\n/activity\nReports,Quarterl\ny,"Ministry of\nSmall,\nMedium\nEnterprise\nDevelopme\nnt\n(MSMED)",161
3,Inspection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
5,Trainings and,Rufunsa,205,205,205,205,205,Number of\ntrainings and\nsednsitisation\ns undertaken,Departme\nntal\n/activity\nReports,Quarterl\ny,"Ministry of\nSmall,\nMedium\nEnterprise\nDevelopme\nnt\n(MSMED)",161
6,Sensitizations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
8,Objective,To promote and strength efficient and effective management of agricultural production and productivity in order to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161
9,,ensure sustainable household and national food and nutrition security and increased incomes by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161

TABLE: 104

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Advisory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
1,services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
3,Crop Production,Rufunsa,17,17,17,17,17,Proportion of\ncrop varieties\nproduced,Departme\nntal\nReports,Quarterl\ny,DACO,162
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
5,Objective,The Local Authority to establish a well-defined public transportation system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
6,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
7,Strategy,Construct public transportation facilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
8,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
9,Programme,Infrastructure Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162

TABLE: 105

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Open up new,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
1,roads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
3,Bridge,Rufunsa\nDistrict,,,,,,Number of\nbridges\nconstructed,Project\nReports,Quarterl\ny,LA,163
4,Construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
6,Bridge,Rufunsa\nDistrict,,,,,,Number of\nbridges\nrehabilitated,Project\nReports,Quarterl\ny,LA,163
7,Rehabilitation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163
9,Installation of,Townships,,,,,,Presence of\nroad signage,Project\nReports,Quarterl\ny,LA,163

TABLE: 106

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Conduct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
1,festivals and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
2,exhibition of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
3,artifacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
5,Promote,District,3,3,3,3,3,Number of\npromotions\nundertaken,Activity\nreport,Quarterl\ny,Culture\nDepartment,164
6,traditional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
7,ceremonies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164
9,Advertise the,National,3,3,3,3,3,Number of\nmedia\nadverts\nplaced,Activity\nreport,Quarterl\ny,Culture\nDepartment,164

TABLE: 107

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Construction of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
1,filling stations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
3,Construction of,District,,1,1,1,,Presence of\ninfrastructure\nConstructed,Project\nReports,Quarterl\ny,PPP,165
4,Banking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
5,facilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
6,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
7,Rehabilitation of,District,1,1,1,1,1,Presence of\ninfrastructure\nRehabilitated,Project\nReports,Quarterl\ny,LA,165
8,existing market,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165
9,shelters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165

TABLE: 108

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Setting up of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
1,Block making,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
2,plant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
3,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
4,Setting up of a,Rufunsa\nTownship,,,1,,,Presence of\nmetal\nfabrication\nworkshop,Project\nReports,Quarterl\ny,LA,166
5,metal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
6,fabrication,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
7,workshop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166
9,Rehabilitation &,Luangwa\nShikabeta,1,1,1,,,Number of\nLodges\nconstructed/r\nehabilitated,LED\nReports,Quarterl\ny,LA,166

TABLE: 109

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,To Improved access to Education for all learners by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167
1,Strategy,"Enhance access to quality, equitable and inclusive eductaion",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167
2,Programme,Upgrading of Community Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167
3,Activities,Locatio,Target,Target,Target,Target,Target,Output,Source of,Frequen,Responsible,167
4,,n (by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,cy,Agency,167
5,NaN,priority,NaN,NaN,NaN,NaN,NaN,,,,,167
6,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,167
7,NaN,),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167
8,Construction,District,5,5,5,5,5,Number\nof CRB\nConstruct\ned,Rufunsa\nDistrict\neducation\nstrategic plan,Quarterl\ny,LA/ MoGEL\nPartners,167
9,of Classroom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167

TABLE: 110

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
2,Construction,District,2,1,1,1,1,Number\nof school\nScience\nlabs\nconstructe\nd,Project\nReport,Quarterl\ny,LA/ MoGEL\nPartners,168
3,of Science,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
4,Laboratories,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
6,Construction,District,1,1,1,1,1,Number\nof school\ncomputer\nlabs\nconstructe\nd,Project\nReport,Quarterl\ny,LA/ MoGEL\nPartners,168
7,of Computer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
8,Laboratories,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168

TABLE: 111

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,To improve health and well being of residents of Rufunsa District by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169
1,Strategy,Public Health Strengthening,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169
2,Programme,Child Health,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169
3,Activities,Locatio,Target,Target,Target,Target,Target,Output,Source of,Frequen,Responsible,169
4,,n (by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,cy,Agency /,169
5,NaN,priority,NaN,NaN,NaN,NaN,NaN,,,,Officers,169
6,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,169
7,NaN,),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,169
8,Conduct,District,34,36,38,40,42,Number\nof\nFacilities\nimplement\ning\nCooking\ndemonstra\ntions,Performance\nAssessment\nReport/Com\nmunity\nRegisters,Monthly,LA/DHO/LPH\nO/MA &\nPartners,169
9,Cooking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169

TABLE: 112

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
1,sensitisations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
3,Health,District,34,36,38,40,42,% of\nPopulatio\nn offered\nhealth\neducation,Activity\nreports,Weekly,LA/DHO/LPH\nO/MA &\nPartners,170
4,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
6,Mentorship of,District,34,36,38,40,42,Number\nof HCWs\nMentored\nin IYCF,District\nTraining Data\nBase/HRIS,Quarterl\ny,LA/DHO/LPH\nO/MA &\nPartners,170
7,Health Care,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
8,Providers in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
9,IYCF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170

TABLE: 113

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Formation of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
1,District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
2,Nutrition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
3,Coordinating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
4,Committees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
5,Training of,District,34,36,38,40,42,Number\nof\ntrainings\nundertake\nn,Activity\nReports,Quarterl\ny,LA/DHO/LPH\nO/MA &\nPartners,171
6,CBVs in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
7,IYCF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171
9,Programme,Promotion of health education across all communities in the district,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171

TABLE: 114

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Quarterly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
1,meetings with,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
2,community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
3,gate keepers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
5,Fire,District,62,65,68,71,74,Number\nof\nsensitisati\non\nmeetings\nundertake\nn,Activity\nReports,Quarterl\ny,LA/DHO/LPH\nO/MA &\nPartners,172
6,prevention,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
7,sensitization,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172
9,Programme,Equip existing structures in communities with health promotion skills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172

TABLE: 115

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Committees-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
1,NHCs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
3,Support,District,590,625,650,700,750,% of\nfacilities\nholding\nNHCs\nmeetings,Number of\nmeeting held,Monthly,LA/DHO/LPH\nO/MA &\nPartners,173
4,quarterly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
5,NHCs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
6,meetings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173
8,Procure,District,50,100,110,30,30,% of\nNHCs\nwith\ncommunit\ny transport,Inventory\nRegister,Monthly,LA/DHO/LPH\nO/MA &\nPartners,173
9,bicycles for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173

TABLE: 116

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Upgrading of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
1,Health,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
2,Facilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
3,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
4,Construction,District,2,2,2,2,2,Number\nof\nMaternity\nWings\nconstructe\nd,Project\nreports,Annually,LA/DHO/LPH\nO/MA &\nPartners,174
5,of Maternity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
6,Wing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174
8,Construction,District,0,0,1,0,0,Presence\nof district\nhospitals,Project\nreports,Annually,LA/DHO/LPH\nO/MA &\nPartners,174
9,of the District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174

TABLE: 117

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,To provide improved access to clean water and sanitation by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175
1,Strategy,Improve access to clean and safe water sources,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175
2,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175
3,Programme,Policy and coordination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175
4,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175
5,Activities,Locatio,Target,Target,Target,Target,Target,Output,Source of,Frequen,Responsible,175
6,,n (by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,cy,Agency,175
7,NaN,priority,NaN,NaN,NaN,NaN,NaN,,,,,175
8,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,175
9,NaN,),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175

TABLE: 118

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Programme,Maintenance of water points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
1,Procurement,District,12,12,12,12,12,Number\nof\ncomplete\ntool kits\nrequested\nto be\nprocured,Internal\nmemorandum,Annually,DWRD /LA/\nPARTNERS,176
2,of tool kits for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
3,Indian Mark II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
5,Programme,Water resources assessment and quantification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
6,Conduct field,District,12,12,12,12,12,Number\nof field\nappraisals\nconducted,Field\nappraisal\nreport,Quarterl\ny,LA,176
7,appraisals for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
8,rehabilitation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176
9,of broken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176

TABLE: 119

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Programme,Training & Capacity Building,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
2,Train and re-,District,12,12,12,12,12,number of\nV -Washe\ntrainings\nundertake\nn,V - Washe\ntraining report,Quarterl\ny,DWRD /LA/\nPARTNERS,177
3,orient V-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
4,Washe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
5,committee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
6,members,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
7,Strategy,Increase access to improved sanitation services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
8,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
9,Programme,Sanitation and Personal Hygiene Promotion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177

TABLE: 120

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Awareness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
1,raising,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
2,(Wards),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
3,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
4,Disability,District,500,600,700,800,900,Number\nof\ndisabled\npersons\ncertified,Activity\nReports,Quarterl\ny,Social Welfare,178
5,Certification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
6,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
7,listing of,District,1500,2000,2500,3000,3500,Number\nof\nbeneficiat\ned listed,Activity\nReports,Quarterl\ny,Social Welfare,178
8,potential,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178
9,beneficiaries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178

TABLE: 121

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,paymets of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
1,cash transfers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
2,to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
3,beneficiaries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
4,Other,District,,,,,,Amount\nof\nadmnistrat\nive costs\nincured,Activity\nReports,Quarterl\ny,Social Welfare,179
5,Amdinistrativ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
6,e Coasts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179
8,Collection Of,District,69,69,72,80,80,Number\nof\ncomplaint\ns attended\nto,Activity\nReports,Quarterl\ny,Social Welfare,179
9,GRM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179

TABLE: 122

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Primary and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
1,secondary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
2,education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
3,support,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
4,community,District,200,300,400,500,600,Number\nof\nvulnerable\npersons\nsupported,Activity\nReports,Quarterl\ny,Social Welfare,180
5,vulnerable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
6,support,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
8,Programme,Women and youth empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180
9,Training of,District,13,13,0,0,0,Number\nof\ntrainings\nundertake\nn,Activity\nReports,Quarterl\ny,Community\nDevelopment,180

TABLE: 123

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Trainers of,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
1,Trainers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
2,training,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
3,workshop in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
4,"Revised life,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
5,sexual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
6,Reproductive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
7,Health and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
8,Business,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181
9,Skills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181

TABLE: 124

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Conduct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
1,mentorship to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
2,SWL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
3,beneficiaries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
5,Payment of,District,281,281,0,0,0,proportion\nof\nbeneficiari\nes\nreceiving\ngrants,Activity\nReports,Quarterl\ny,Community\nDevelopment,182
6,Grants for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
7,SWL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
8,beneficiaries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182

TABLE: 125

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Revamping,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
1,and formation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
2,of literacy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
3,classes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
5,Procure,District,4,4,4,4,4,Number\nof training\nmaterial\nprocured,Activity\nReports,Quarterl\ny,Community\nDevelopment,183
6,Teaching,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
7,material,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183
9,Programme,Food Security Pack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183

TABLE: 126

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
1,"validation,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
2,Self-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
3,registration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
4,and Lottery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
5,Training of,District,1300,1500,1700,1900,2000,Number\nof\ntrainings\nundertake\nn,Activity\nReports,Quarterl\ny,Community\nDevelopment,184
6,Vulnerable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
7,but Viable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
8,farmers into,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
9,farming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184

TABLE: 127

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
2,Programme,Constituency Development Fund,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
3,Empowermen,District,200,200,200,200,200,Number\nof\nbeneficiari\nes,CDF Reports,Quarterl\ny,LA,185
4,t Grants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
6,Empoweremn,District,50,50,50,50,50,Number\nof\nbeneficiari\nes,CDF Reports,Quarterl\ny,LA,185
7,et Loans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185
9,Secondary,District,800,800,800,800,800,Number\nof\nstudents\nsupported,CDF Reports,Quarterl\ny,LA,185

TABLE: 128

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,Increased adaptive Capacity to Climate Change by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186
1,Strategy,Strengthen Climate Change Adaptation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186
2,Programme,Community education and awareness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186
3,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186
4,Activities,Locatio,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,186
5,,n (by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Informat,uenc,le Agency,186
6,NaN,priority,NaN,NaN,NaN,NaN,NaN,,ion,y,,186
7,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,186
8,NaN,),NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,186
9,Conduct sensitisation,District,12,12,12,12,12,Number of\nawareness\nmeetings\nheld,Activity\nReport,Quar\nterly,Forestry,186

TABLE: 129

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Bio-diversity monitoring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
2,Programme,climate Change Adaptation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
3,sensitisation and,District,2,2,2,2,2,Number of\ntrainings\nundertaken,Activity\nReport,Quar\nterly,LA/HIVOs,187
4,trainings on diverse food,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
5,systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
6,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
7,Trainings on Food,District,4,4,4,4,4,Number of\ntrainings\nundertaken,Activity\nReport,Quar\nterly,LA/HIVOs,187
8,Preservation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187

TABLE: 130

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Programme,Environmental Regulations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
1,Conduct enforcement of,District,10,10,10,10,10,Number of\nenforcemen\nt nts\nundertaken,Activity\nReport,Quar\nterly,LA,188
2,environmental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
3,regulations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
5,Environmental and,District,12,12,12,12,12,Number of\nassessment\ns\nundertaken,Activity\nReport,Quar\nterly,LA,188
6,Social Impact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
7,Assessments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
8,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188
9,Programme,Environmental Protection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188

TABLE: 131

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Programme,Procurement of refuse management equipment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
2,Procurement of a refuse,Rufunsa,0,1,0,0,0,Presence\nof rufuse\ntruck,Activity\nreport,Ann\nually,LA,189
3,truck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
5,Procurement of a refuse,,0,0,0,1,0,Presence\nof rufuse\ntruck,Activity\nreport,Ann\nually,LA,189
6,skip collector,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
7,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
8,Procurement of refuse,Rufunsa\nDistrict,0,20,20,20,20,Number of\nrufuse bins\nprocured,Activity\nReport,Quar\nterly,LA,189
9,bins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189

TABLE: 132

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,To enhance citizen participation in development by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
1,Strategy,Operationalise Ward Development Committees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
2,Programme,Ward Development Committees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
3,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,189
4,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,uenc,le Agency,189
5,NaN,priority),NaN,NaN,NaN,NaN,NaN,,,y,,189
6,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,189
7,Orientation of,District,12,12,12,12,12,Number of\nWDCs\noriented,Activity\nReport,Quart\nerly,LA,189
8,WDCs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189

TABLE: 133

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,190
1,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,uenc,le Agency,190
2,NaN,priority),NaN,NaN,NaN,NaN,NaN,,,y,,190
3,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,190
4,"Production of\nbrochures,\nmagazines and\npop up stands",Civic Center\ninformation\ndesk,1100,1100,1100,1100,1100,Number of\nIEC\nmaterials\nproduced,Activity\nReport,Quart\nerly,LA,190
5,Sensitisation,Rufunsa,4,4,4,4,4,Number of\nsensitsatio\nn\nundertake\nn,Activity\nReport,Quart\nerly,LA,190
6,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190
7,Procurement of,Rufunsa,,1,,,,Presence\nof PA\nsystem,Activity\nReport,Annu\nally,,190
8,PA System,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190
9,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190

TABLE: 134

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,To improve the registration of land,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191
1,Strategy,Strengthening Land registration systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191
2,Programme,Land Management and Administration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191
3,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,191
4,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,uenc,le Agency,191
5,NaN,priority),NaN,NaN,NaN,NaN,NaN,,,y,,191
6,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,191
7,Development,Rufunsa\nShikabeta\nTownships,1,1,-,-,-,Presence\nof LAP,Activity\nReport,Annu\nally,LA,191
8,of LAP in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191
9,Sinjela and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191

TABLE: 135

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Strategy,Strengthen public serve performnace and management systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192
1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192
2,Programme,ICT for public service delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192
3,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,192
4,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,uenc,le Agency,192
5,NaN,priority),NaN,NaN,NaN,NaN,NaN,,,y,,192
6,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,192
7,Formulation,Township,1,,,1,,Presence\nof ICT\nPolicy,Activity\nReport,Annu\nally,LA,192
8,and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192
9,Implementatio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192

TABLE: 136

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,193
1,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,uenc,le Agency,193
2,NaN,priority),NaN,NaN,NaN,NaN,NaN,,,y,,193
3,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,193
4,Setting up of,District,0,0,1,0,0,Presence\nof radio\nstation,Project\nReports,Annu\nally,LA/\nPartners,193
5,community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193
6,Radio Station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193
7,Completion of,Township,0,0,1,0,0,Presence\nof post\noffice,Project\nReports,Annu\nally,MOI,193
8,Rufunsa Post,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193
9,Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193

TABLE: 137

,0,1,2,3,4,5,6,7,8,9,10,source_page
0,Objective,To provide District Administration infrastructure to support governance systems by 2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194
1,Strategy,Completion of on-going government infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194
2,Programme,Infrastructure Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194
3,Activities,Location,Target,Target,Target,Target,Target,Output,Source of,Freq,Responsib,194
4,,(by,Year 1,Year 2,Year 3,Year 4,Year 5,Indicator,Information,uenc,le Agency,194
5,NaN,priority),NaN,NaN,NaN,NaN,NaN,,,y,,194
6,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,194
7,Construction,Township,0,1,0,0,0,Presence\nof\nInfrastruct\nure,Project\nReports,Annu\nally,MIHUD,194
8,of District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194
9,Admin Block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194

In [38]:
idp_df = pd.concat(
    all_tables,
    ignore_index=True
)

print("IDP dataset shape:", idp_df.shape)

display(idp_df.head(10))

IDP dataset shape: (2324, 12)

,0,1,2,3,4,5,6,7,8,source_page,9,10
0,2010 Population,NaN,NaN,2022 Population,NaN,NaN,Average Annual Population\nGrowth Rate 2010- 2022,NaN,NaN,22,NaN,NaN
1,Male,Female,Total,Male,Female,Total,Male,Female,Total,22,NaN,NaN
2,"25,785","25,217","51,002","41,478","40,255","81,733",4.0,4.0,4.0,22,NaN,NaN
3,Population,Land Area,Population Density (Pop/Land\nArea),NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
4,"82,347","9,446.0",8.7,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
5,Age Group,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
6,0-9,"16,619",NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
7,10-19,"13,455",NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
8,20-29,"7,144",NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN
9,30-39,"5,029",NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,NaN

## Clean the IDP project data

In [39]:
idp_df.columns = (
    idp_df.columns
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

# remove empty records:
idp_df = idp_df.dropna(how="all")
idp_df = idp_df.dropna(axis=1, how="all")

# removing duplicates
idp_df = idp_df.drop_duplicates()

# Add metadata
idp_df["council"] = "Rufunsa Town Council"
idp_df["province"] = "Lusaka Province"
idp_df["district"] = "Rufunsa"
idp_df["constituency"] = "Rufunsa"
# Add
idp_df["council"] = "Rufunsa Town Council"
idp_df["province"] = "Lusaka Province"
idp_df["district"] = "Rufunsa"
idp_df["constituency"] = "Rufunsa"

## Validate IDP data

In [40]:
print(idp_df.shape)

print(
    idp_df.isna().sum()
)

print(
    "Duplicates:",
    idp_df.duplicated().sum()
)

idp_df["sector"].value_counts()

(2037, 16)
0                399
1                774
2               1025
3               1087
4               1116
5               1203
6               1235
7               1277
8               1306
source_page        0
9               1548
10              1786
council            0
province           0
district           0
constituency       0
dtype: int64
Duplicates: 0

KeyError: 'sector'

In [41]:
idp_output = (
    "../data/cleaned/"
    "db-unza26-csc4792-rufunsa_idp_projects.csv"
)

idp_df.to_csv(
    idp_output,
    sep="|",
    index=False
)

In [42]:
idp_output = (
    "../data/cleaned/"
    "db-unza26-csc4792-rufunsa_idp_projects.csv"
)

idp_df.to_csv(
    idp_output,
    sep="|",
    index=False
)

In [33]:
idp_path = "../data/raw/rufunsa_idp.pdf"

## Ward Dataset
A. Target columns
* ward_id
* council
* province
* district
* constituency
* ward_name
* councillor
* source_url
* retrieval_date